### ISSUE TITLE
Provide import & export methods to upgrade versions

### ISSUE THREAD

**Issue by cberner** [cberner/redb#100]
The interface sled provides seems good: https://docs.rs/sled/latest/sled/struct.Db.html#method.import

**Comment by cberner** [comment]
I decided this is not a good idea, since it could limit the ability to add new features. For example, storing type names with table definitions could not be done in a backwards compatible way

**Comment by dignifiedquire** [comment]
Any suggestions on how to deal with upgrades between different versions instead? 

This pattern

```
let old = old_sled::open("my_old_db")?;

// may be a different version of sled,
// the export type is version agnostic.
let new = sled::open("my_new_db")?;

let export = old.export();
new.import(export);

assert_eq!(old.checksum()?, new.checksum()?);
```

would be really nice for us, being able to deal with development changes.

**Comment by cberner** [comment]
Ya, I'd suggest something like:
```
let new = Database::create(new_path);
let old = Database::open(old_path);
let new_table = new.open_table(TABLE);
let old_table = old.open_table(TABLE);

for (k, v) in old_table.iter() {
  new_table.insert(&k, &v);
}
```

Unfortunately it's unlikely that redb will have import/export methods due to the limitations that would impose. However, the file format is getting fairly close to being done, so I hope to have it finalized later this year
