### ISSUE TITLE
Add TableHandle API

### ISSUE THREAD

**Issue by cberner** [cberner/redb#109]
This needs [adt_const_params](https://github.com/rust-lang/rust/issues/44580) to allow const generic &str

The API should work like:
```
struct TableHandle<const name: &str, K, V>
```

then opening a table would be like:
```
type MY_TABLE = TableHandle<"my_table", u64, [u8]>

db.open_table::<MY_TABLE>();
```

**Comment by cberner** [comment]
@casey what do you think of this as an implementation of the improvement to the current `open_table()` API that you suggested?

**Comment by casey** [comment]
Looks good to me! Type names should be pascal-case, so it would be:

```rust
type MyTable = TableHandle<"my_table", u64, [u8]>;
db.open_table::<MyTable>();
``

**Comment by casey** [comment]
Can you use a trait to avoid needing adt_const_params? I.e.:

```rust
trait TableHandle {
    const NAME: &'static str;
    type Key: KeyTrait;
    type Value: ValueTrait;
}
```

It's more verbose, since you have to declare a unit type `struct MyTable;` and then implement the trait.

**Comment by cberner** [comment]
Ya, I can definitely do a trait instead. It just seemed annoying to force users to implement a trait for every table, so I wanted to have both a trait and a struct that implements the trait and can be used as a generic. If adt_const_params takes too long though, I'll probably go ahead with the trait

**Comment by casey** [comment]
I was looking at this, and had the thought that although macros are a bit gross, it might be a worthwhile stopgap.

Declaring a table named `Foo` with key type `u64` and value type `[u8]` could look something like:

```rust
redb::table!(Foo, u64, [u8]);
```

It could expand to:

```
struct Foo;

impl TableHandle for Foo {
  const NAME: &'static str = "Foo"; // via stringify! macro
  type Key = u64;
  type Value = [u8];
}
```

A nice side-effect of this API is that since the name of the struct is the name of the table, it is a compilation error to have two `redb::table!` declarations with the same table name, as long as they're all declared in the same module.

If the actual implementation isn't stable yet, you could hide the docs for `TableHandle`, so that users are less likely to use it directly.

Also, I was thinking that maybe `TableDefinition` would be a better name than `TableHandle`, since it's not exactly a handle per-se, it's something that you can pass to `open` to get a handle. The macro could then be called `redb::table_definition!`.

**Comment by cberner** [comment]
That could work. I was just thinking about this issue the other day, and started wondering if it's that important. The main benefit I can see is type safety. But it only partially solves that problem, because you can still change your code to have different types on your table, load an old database, and get garbage values.

So I was thinking about storing the types in the database, and disallowing users from defining their own types. Can you think of a compelling use case that requires user defined types?

**Comment by casey** [comment]
> That could work. I was just thinking about this issue the other day, and started wondering if it's that important. The main benefit I can see is type safety. But it only partially solves that problem, because you can still change your code to have different types on your table, load an old database, and get garbage values.

I think it's good for correctness and maintainability, even if it doesn't guarantee type-safety. If you are opening the same table in different places, you have to repeat the same type-definitions in different places, and it would be nice not to have to keep them in sync.

> So I was thinking about storing the types in the database, and disallowing users from defining their own types. Can you think of a compelling use case that requires user defined types?

We already have an instance where we're inserting two logically-related values into the database under one key, so if user-defined types were available, we'd definitely use them.

**Comment by cberner** [comment]
> I think it's good for correctness and maintainability, even if it doesn't guarantee type-safety. If you are opening the same table in different places, you have to repeat the same type-definitions in different places, and it would be nice not to have to keep them in sync.

Ah got it, the benefit is more about improved type inference, so that you don't need `let table: Table<u32, u32> = ...` everywhere, yes?

It looks like `const_impl_trait` is going to be [stabilized soon](https://github.com/rust-lang/rust/pull/93827), at which point I can do:
```
pub struct TableHandle<'a, K: RedbKey + ?Sized, V: RedbValue + ?Sized> {
    name: &'a str,
    _key_type: PhantomData<K>,
    _value_type: PhantomData<V>,
}

impl<K: RedbKey + ?Sized, V: RedbValue + ?Sized> TableHandle<K, V> {
    pub const fn new(name: &str) -> Self {
        Self {
            name,
            _key_type: PhantomData,
            _value_type: PhantomData,
        }
    }
}
```

and you'll be able to do: `const MY_TABLE = TableHandle::new(...)`

In the mean time, I could implement it without `const`, and you could instead use a top-level function like: 
```
pub(crate) fn my_table() -> TableHandle {
}

db.open(my_table()).unwrap()
```

What do you think of that?

And ya, "handle" doesn't seem quite right. I wonder if I should just call it `Table` and then rename the current `Table` to `WritableTable` or some such

**Comment by cberner** [comment]
In fact, can you think of a way to abuse [this](https://github.com/rust-lang/rust/issues/90912) to get `const` to work now? :)

**Comment by casey** [comment]
> What do you think of that?

That sounds great!

> And ya, "handle" doesn't seem quite right. I wonder if I should just call it Table and then rename the current Table to WritableTable or some such

I think that sounds good. `WritableTable` isn't great, because it sounds like it's the same thing as a `Table`, only writable. `TableHandle` would actually be a good name for what's currently called a `Table`. Maybe `TableHandle` and `WritableTableHandle`?

> In fact, can you think of a way to abuse https://github.com/rust-lang/rust/issues/90912 to get const to work now? :)

I think not, since I don't think that can be used to slip in a `&const str`.

**Comment by cberner** [comment]
Turns out I was able to make `const` work :) Just had to remove the trait bounds for the moment, but that doesn't really matter, since you can't use a TableDefinition without the right Key & Value types

**Comment by casey** [comment]
Sweet, seems to work: https://github.com/casey/ord/pull/143

**Comment by cberner** [comment]
Awesome!
