### ISSUE TITLE
Automatic resizing

### ISSUE THREAD

**Issue by casey** [cberner/redb#147]
It would be really nice if it were possible to not specify an initial size of the database, and let it resize whenever needed. Especially because often, if you're responding to external events or indexing some growing set of data, you don't have a good idea how much space is needed.

**Comment by cberner** [comment]
Ya, that'd definitely be nice. I looked into it briefly, and am still a bit unclear on how doable it is without making performance sacrifices, because of the implications from using mmap

**Comment by casey** [comment]
Is it hard to shrink, or hard to grow?

I would sort of assume that growing the size of the database file would be easier. I read a bit, and it sounds like you might be able mmap more space than the file actually contains (which will produce an error if you try to read it, but is fine on the initial mapping) and then increase the space of the file with seek and write, or with ftruncate.

**Comment by cberner** [comment]
Ya, shrinking is really hard. I think to do online shrinking I'd basically have to build a relocating garbage collector.

Growing is easier, but still a bit tricky. I'd thought I would need to unmap and remap the file, but if you're right about being able to map extra address space upfront that solves the biggest issue. 
The other main problem is around performance. When increasing the db size, I have to recreate the b-tree that's used for the buddy allocator of pages. It's about 0.1% of the database, so could be a GB or so for a big database. Doing that inline would lead to a pause during modification, and I kind of hate unpredictable performance like that. Making the rewrite of that data structure be incremental would be pretty annoying though.

**Comment by casey** [comment]
> Growing is easier, but still a bit tricky. I'd thought I would need to unmap and remap the file, but if you're right about being able to map extra address space upfront that solves the biggest issue.

Fingers crossed I'm right. This random email thread is my reference, so take it with a grain of salt:

https://groups.google.com/g/comp.os.linux.development.system/c/l1ZNR5Pq4Ws

LMDB seems to not support resizing online, which would be strange if it were so easy:

http://www.lmdb.tech/doc/group__mdb.html#gaa2506ec8dab3d969b0e609cd82e619e5

> When increasing the db size, I have to recreate the b-tree that's used for the buddy allocator of pages.

Am I understanding correctly that the issue is that you initialize the allocator b-tree with a bunch of pages, and then if you increase the database size, you need to recreate the b-tree with all the new pages?

You could include all the pages, including unbacked pages from at the end of the mapping. Then, if the allocator is about to return an unbacked page, you ftruncate the file to the end of the unbacked page.

Would that work?

**Comment by casey** [comment]
For my own reference, at a high level, what's in the database? There's the allocator b-tree, and then there's the b-tree that contains the keys and values. Are there other top level data structures?

**Comment by cberner** [comment]
> Am I understanding correctly that the issue is that you initialize the allocator b-tree with a bunch of pages, and then if you increase the database size, you need to recreate the b-tree with all the new pages?

Yep, there's a b-tree that's statically initialized with enough space to store a boolean (allocated/free flag) for each page. So if pages are added it needs to be rebuilt and expanded.

> You could include all the pages, including unbacked pages from at the end of the mapping. Then, if the allocator is about to return an unbacked page, you ftruncate the file to the end of the unbacked page.
> 
> Would that work?

Yes, except then for small databases it would take up a lot of space -- say I allow 10TB of unbacked pages for future growth, then there would be ~10GB of overhead from the allocator, even in an empty database

**Comment by cberner** [comment]
> For my own reference, at a high level, what's in the database? There's the allocator b-tree, and then there's the b-tree that contains the keys and values. Are there other top level data structures?

I have a [design doc](https://github.com/cberner/redb/blob/master/docs/design.md), in fact :) It might be a little out of date, so summary of the latest is:
The database is laid out as:
```
| db metapage | b-trees.............. | allocator state 0 | allocator state 1 |
```
The metapage contains very little, just the metadata like page size, max db size, file format version, and then most importantly the root page number, the shadow copy of the root page number, and the bit that says which root page number buffer is the primary

In the b-trees section there are at least 2 trees:
1) the mapping of table names to root page numbers of those tables
2) the freed table, which stores pages freed by old transactions which can't be freed yet because an open read transaction is still using them
then there's 1 b-tree for each table, and it's root is stored in table (1)

The allocator state is the buddy allocator I was talking about above. There are two copies of it to match the two root page buffers in the metapage. I might change it to have just one copy, but two can be useful for bounding memory usage (RAM, not mmap'ed memory)

**Comment by casey** [comment]
> Yes, except then for small databases it would take up a lot of space -- say I allow 10TB of unbacked pages for future growth, then there would be ~10GB of overhead from the allocator, even in an empty database

Gotcha. Two thoughts:

1. When you mentioned that you were using a buddy allocator, my dim memories of 61c kicked in, and I thought that maybe you meant an allocator that starts with a single large block of memory, and then recursively splits it to return an allocation. If you were using an allocator like that, you could initialize it with a single block, i.e. the whole mapping, which would mean a tree with just a single entry, and then split it recursively when you needed an allocation, so the tree would only get large when there were a lot of allocations. Would that work?

2. Assuming there's no way around the overhead, then a nice API would be if `Database::open` took the maximum size of the database. On open, it would create a mapping of that size, and allocate just enough space in the actual backing file to store the allocator tree with allocations for the maximum size, but no space for the actual data. Then, as data was inserted into the database, it would grow the backing file, up to the maximum size, to store the data. That way, users could control how much overhead they were willing to tolerate.

**Comment by casey** [comment]
> I have a [design doc](https://github.com/cberner/redb/blob/master/docs/design.md), in fact :) It might be a little out of date, so summary of the latest is: The database is laid out as:

Thanks, that's super helpful!

**Comment by cberner** [comment]
1) yep, that's the algorithm I'm using! However, because the tree can be so large (GBs) and I don't want to do any copying of large amounts of memory, I statically allocate space for every page of every size to avoid needing to grow anything. It also simplifies the code to allocate all the space ahead of time. 
The current layout places the levels of the tree sequentially in memory, so the root is followed by level1, followed by level2, which doesn't lend itself well to dynamically growing the data structure. That could certainly be changed though.

Overall, this does seem like the best approach to doing automatic resizing, assuming mmap'ing extra address space is safe.

2) On filesystems that support sparse files (e.g. ext4) you sort of get this behavior already. Initializing a `Database` only writes the allocator structure and the metapage, the data section isn't written until you insert into a table. For example, I just tried creating a 100GB redb database, and even though the file is 100GB:
```
-rw-rw-r-- 1 cberner cberner 100G Feb  2 19:49 int_keys.redb
```
My free space didn't decrease at all:
```
#before
/dev/mapper/ubuntu--vg-root         467G  299G  144G  68% /

#after
/dev/mapper/ubuntu--vg-root         467G  299G  144G  68% /

```

**Comment by casey** [comment]
> 2. On filesystems that support sparse files (e.g. ext4) you sort of get this behavior already. Initializing a `Database` only writes the allocator structure and the metapage, the data section isn't written until you insert into a table. For example, I just tried creating a 100GB redb database, and even though the file is 100GB:

I just checked, and this also applies to APFS. I created a 2tib database, and my available space as measured by `df -h` didn't decrease at all. So this mostly solves my practical problems. I can create a very large database, at the upper limit of what I expect to need, and it won't actually take up any space. There is some weirdness, like `cp`ing a sparse file on macos seems to create a non-sparse copy, and it would be nice to see how much data is actually being used in the db, so max-size-plus-resizing would still be nice to have, although not as critical.

**Comment by cberner** [comment]
Awesome, I was hoping that worked on APFS too!

Ya, relying on sparse files is not great. I'll give some more thought to whether I can restructure the page allocator, so that automatic resizing can be done online

**Comment by cberner** [comment]
> Fingers crossed I'm right. This random email thread is my reference, so take it with a grain of salt:
> 
> https://groups.google.com/g/comp.os.linux.development.system/c/l1ZNR5Pq4Ws
> 
> You could include all the pages, including unbacked pages from at the end of the mapping. Then, if the allocator is about to return an unbacked page, you ftruncate the file to the end of the unbacked page.
> 
> Would that work?

Read through the thread, ya sounds like this will work as long as I call `mremap` after increasing the file size. Otherwise access to the new parts of the file is undefined behavior. Now I just need to figure out if Windows supports the same remapping

**Comment by casey** [comment]
Using LMDB, and it looks like when you create a database, the file starts small and LMDB increases it as data is inserted. Do you know how LMDB does this?

**Comment by cberner** [comment]
I don't, but I started on my own region-based memory allocation approach that'll make this work and also make the database shrinkable

**Comment by casey** [comment]
Dope!
