### ISSUE TITLE
Allow opening a databse without passing in the size

### ISSUE THREAD

**Issue by casey** [cberner/redb#150]
It would be nice to have separate open and create calls. My use-case is this:

- I want to allow the user to pass in the database size when creating the database
- However after that, the user shouldn't have to pass in the database size

This could be accomplished with separate `open` and `create` static methods on `Database`, similar to `File::open` and `File::create`. Open would open an existing database, and so wouldn't need to take the size, and create would create a new database, and so would need to take the size. (Create could also open an existing database of the right size, a la the current `Database::open`.)

**Comment by cberner** [comment]
Ya, I think this is a great idea! I need to revisit several of the public API methods
