### ISSUE TITLE
Document DbStats::fragmented_bytes

### ISSUE THREAD

**Issue by casey** [cberner/redb#176]
What does `DbStats::fragmented_bytes` measure? I couldn't figure it out. For example, I expected it to be low for a freshly created database, but on a database with no insertions, `fragmented_bytes` was 16346.

**Comment by cberner** [comment]
It measures the number of unused bytes in allocated pages. It includes internal metadata pages, like the btree of table names, so I'd expect it to be `4k - epsilon` for an empty db. Did you create any tables before checking the fragmented bytes?

**Comment by casey** [comment]
There are two tables, one which will have an entry per block, and one which will have an entry per output, and they're both empty. This is what the stats look like for a new 1MiB database:

```
blocks indexed: 0
outputs indexed: 0
tree height: 1
free pages: 61
stored: 0 bytes
overhead: 38 bytes
fragmented: 15.96 KiB
```

I think my disk has 4KiB blocks:

```
$ diskutil info /Volumes/Root | grep 'Block Size'
   Device Block Size:         4096 Bytes
   Allocation Block Size:     4096 Bytes
```

But fragmented is suspiciously close to 16KiB, and 1MiB / 64 (which is close enough to 61) == 16KiB. Is it possible that for some reason redb is using 16KiB pages?

**Comment by casey** [comment]
I just checked, and `sysconf(_SC_PAGESIZE)` does indeed return 16384, so the fragmented value make sense.

Is there a disadvantage to setting the page size to be smaller? It seems like it would reduce fragmentation.

**Comment by cberner** [comment]
Ya, it will reduce fragmentation. It might not be that much though, once you start writing data into the tables. The downside is that it could hurt performance, but I haven't experimented with it

**Comment by casey** [comment]
I think maybe my mental model might be wrong.

When redb allocates space for an b-tree node, can it put multiple nodes inside of a single page, or does it have to allocate a page per node? And same question for keys and values, can it store multiple keys and values inside of a single page, or does it need to allocate a page for each?

**Comment by cberner** [comment]
So there are two different types of pages that come into play:
1) OS pages: the page size your OS uses
2) redb pages: these are dynamically sized in powers of two. The minimum size is configured when you create the database, and defaults to the OS page size

b-tree nodes map 1:1 to pages, and redb uses some heuristics to try and fit them into the smallest page size. For example, it will split any leaf pages with > 1 entry that exceeds the configured minimum page size.

A node can store many keys & values, up to `BTREE_ORDER` which is a constant in `btree_base.rs` and currently defined to be `40`. I may remove that constant at some point, and just store as many as can fit in a page.

**Comment by casey** [comment]
Okay, that makes sense. It’s too bad that the word page is overloaded to
mean both OS page and b-tree page, but those are the standard terms, so it
can’t really be helped.

So if key/value pairs are small, relative to the minimum page size, then
all pages will be the minimum size, and it’s only when keys and values are
larger will redb make larger allocations.
