### ISSUE TITLE
Key and value implementations for tuples

### ISSUE THREAD

**Issue by casey** [cberner/redb#180]
Would it be easy to implement the key and value traits for tuples of various lengths, where the tuple element types implement the key or value trait? I keep wanting to stick additional things into my keys and values, and this would allow that, without requiring serializing them to a byte array.

**Comment by cberner** [comment]
Seems like it should be easy, but I think it requires generic associated types. Do you have any ideas for getting around this lifetime error? I pushed the code to the ["tuples" branch](https://github.com/cberner/redb/commit/b91d9936aaab1b81e4655b3ba522adcd6c69beed)

```
error[E0106]: missing lifetime specifier
   --> src/types.rs:101:22
    |
101 |         <T0::View as WithLifetime>::Out,
    |                      ^^^^^^^^^^^^ expected named lifetime parameter
    |
help: consider introducing a named lifetime parameter
    |
100 ~     type View<'a> = (
101 ~         <T0::View as WithLifetime<'a>>::Out,
    |

error[E0106]: missing lifetime specifier
   --> src/types.rs:102:22
    |
102 |         <T1::View as WithLifetime>::Out,
    |                      ^^^^^^^^^^^^ expected named lifetime parameter
    |
help: consider introducing a named lifetime parameter
    |
100 ~     type View<'a> = (
101 |         <T0::View as WithLifetime>::Out,
102 ~         <T1::View as WithLifetime<'a>>::Out,
    |

```

**Comment by casey** [comment]
I'm wondering if you could refactor the types such that `RedbValue::View` doesn't require a lifetime at all. This is a shot in the dark, since I only took a brief look, and don't fully understand how all the types fit together.

Lifetimes can appear in two ways, they can be generic parameters of a type, or they can be attached to a reference:

- `Foo<'a>`
- `&'a Foo`

Can the lifetime of the `View` types be refactored to be reference lifetimes, instead of parameters?

i.e.:

```
// from this:
fn get_view<'a>(source: &'a) -> View<'a> {
  …
}

// to this:
fn get_view<'a>(source: &'a) -> &'a View {
  …
}
```

If so, then you might be able to get rid of the lifetime parameter, and avoid needing GATS.

Formulating things with reference lifetimes requires unsafe. In the above example function, for example, you might need to do an unsafe transmutation from the `source` reference to the return reference, which is safe when you know that the types have the same layout.

**Comment by casey** [comment]
Ah okay, I think I see why this isn't currently possible, `RedbValue::from_bytes` can return an owned or a borrowed value, so it can't return `&'a Self::View::Out`.

You could consider changing this so that it always returns a borrowed value, but that would require returning `redb::U64` instead of `u64`, and needing to call `U64::into()`, or something, to convert into a normal u64, due to endianness and alignment issues.

**Comment by casey** [comment]
Jk, that doesn't work for tuples, because tuple layout is not defined, so you can't return a reference to a tuple, even if you could return a reference to all the individual types in the tuple.

**Comment by cberner** [comment]
@casey I think I've got tuple types working on my branch with GATs :) https://github.com/cberner/redb/tree/tuples

There's one oddity. For the `&str` and `&[u8]` types, I have currently implemented them for tables as `Table<str, [u8]>`. This is nice because then the lifetime parameters don't spread everywhere. 
However, this doesn't work for tuples, because if I define the table as `Table<str, (str, str)> `.insert()` takes a `&K` and `&V` and you can't construct a `(str, str)`. So I had to implement `RedbValue` for `&str` and also for `str`, so that you can have both `Table<str, str>` and `Table<str, (&str, &str)>`. Alternately, I could just implement it for `&str`, but then it'd force people to add lifetimes if they wanted to put a Table into another struct.

Any thoughts on this?

**Comment by casey** [comment]
No clever workarounds come to mind. This is kind of why that serialization format I was writing had these intermediate types, since tuples or structs containing raw references present these kinds of difficulties.

One thing you could consider is looking for an existing serialization format that handles these problems, and using that for more complex types, like tuples, for example [rkyv](https://github.com/rkyv/rkyv), that seems actively developed.
