### ISSUE TITLE
Consider treating missing tables as merely empty during read transactions

### ISSUE THREAD

**Issue by casey** [cberner/redb#182]
I'm running into an ergonomic issue where if a table hasn't been created, querying the database for that table will return an error.

For example, if I start up my index, but there aren't any blocks, and thus nothing gets inserted, reads of the tables that would be created during those insertions return errors.

To handle this case correctly, I need to check the error to see if it's a table not found error.

I was thinking that it might be nice to treat non-existent tables as simply being empty. This would cause queries against an applications uninitialized database to simply behave as it was initialized with tables, but that they are all empty.

This would simplify application code, and a lot of the time is has the right semantics. The main downside I can think of is that if you misspelled a table name, it would tell you that it was empty instead of telling you that it doesn't exist.

**Comment by casey** [comment]
This also would make read transactions behave more like read/write transactions, since when you open a non-existent table in a write transaction, it behaves as if the table is empty.

**Comment by cberner** [comment]
Ya, I see the argument for that behavior, but I think the current behavior is better, because I like more explicit error handling. It  also [matches lmdb](http://www.lmdb.tech/doc/group__internal.html#gac08cad5b096925642ca359a6d6f0562a): `MDB_CREATE: Create the named database if it doesn't exist. This option is not allowed in a read-only transaction or a read-only environment.`

**Comment by casey** [comment]
I see the argument for explicit error handling, although I wonder how often it would actually be error, given that the table-handle API makes it hard to misspell a table name. The only case I can think of where it would actually prevent a bug would be when you opened a table, and expected it to have been initialized or populated with data, and the application code didn't handle it being empty well. Although I suppose you would just get `None` when you tried to access the data, which would be a good indication of what was up, although not as clear as a table-doesn't-exist error.

**Comment by cberner** [comment]
So, even in the case where the application handles an empty database well, it could mask ordering problems in your application. Like if you have a multithreaded application, and one thread does the initialization, you probably want that thread to complete before serving requests.

**Comment by casey** [comment]
That's a good point. I guess doing an idempotent initialization step, and just doing it before everything, is the best way to avoid having to check for non-existent tables.
