### ISSUE TITLE
Add method to do explicit compaction

### ISSUE THREAD

**Issue by cberner** [cberner/redb#20]

**Comment by jeromegn** [comment]
Just to be sure I understand the model for storage here:
- `redb` databases will automatically grow to accommodate to fulfill space requirements of the data stored
- Pages are reused in some cases
- Pages are never "freed"

So that would mean until there's compaction the database cannot shrink, only grow.

Ideally, users of this crate should periodically clean up their data when possible for maximum page reuse if they don't want the database to grow too much?

**Comment by cberner** [comment]
> Pages are never "freed"

Actually no, pages are freed when transactions are committed. There is also some very limited support for shrinking the database, but it only works in very specific cases. 

This issue is about adding an explicit API to do offline (data cannot be read or written during compaction) compaction and defragmentation of the database file.

**Comment by jeromegn** [comment]
> Actually no, pages are freed when transactions are committed.

"freed" as in "freed for reuse" or freeing up disk space?

> There is also some very limited support for shrinking the database, but it only works in very specific cases.

That's interesting. In what cases does it work? I assume something to do with the perfect conditions aligning (e.g. consecutive, deleted, data freeing up a whole "thing" (page?))

I'm not criticizing btw, trying to learn more about the tradeoffs of `redb` :)

**Comment by cberner** [comment]
Freed for reuse. It won't change the size of the file, except in the case below.

> That's interesting. In what cases does it work? 

It works in the case that the last 2GB (or half the database, if it's less than 4GB) of the database file are completely freed. redb has an internal concept of a "region" which is up to 4GB in size

**Comment by jeromegn** [comment]
I've switched our project from `persy` to `redb` and noticed the size is quite a lot bigger. For the same dataset (keys and values should be approximately the same size), `persy` uses ~1GB, while `redb` uses ~4GB on disk and growing.

My DB stats:
```
tree_height = 6
allocated_pages = 572837
leaf_pages = 544516
branch_pages = 15579
stored_bytes = 1104053130
metadata_bytes = 140792550
fragmented_bytes = 1100921232
page_size = 4096
```

We have a mechanism to shrink the database by copying only the most recent data (partially truncating it) into a new database. For `persy` this brought down our database from 15GB to 700MB by getting rid of all the pages that couldn't be completely freed. For `redb` the 4GB is the result I got from migrating from a ~1GB `persy` database.

A related issue (https://github.com/cberner/redb/issues/171) made me wonder if my transactions were too big, leading to bigger preventive growth. I reduced them to 1000 inserts at most for each transaction. Of course the size of the data varies a lot, I could likely restrict it by size too.

Are there settings I could be tweaking? I'm using the checksum write strategy, the rest is set to defaults.

If you'd rather I start a different issue about this, I'm happy to!

**Comment by cberner** [comment]
Ya, unfortunately what you're seeing is expected with the current redb growth heuristics. redb will always have about 1/3 to 1/2 the database space be "fragmented" and therefore it's overhead. That accounts for the fact that you see about 1GB of "stored" and "fragmented" space. Then on top of that the database file grows by a factor of 2x everytime it fills up, until it reaches 4GB. Since you have > 2GB (counting the fragmentation) the file is rounded up to 4GB

**Comment by cberner** [comment]
Oh, one thing you could try is `Builder::set_initial_size()`. If you set that to > 2GB and < 4GB, you might be able to avoid the fact that it rounds up to 4GB
