### ISSUE TITLE
Durability guarantees

### ISSUE THREAD

**Issue by casey** [cberner/redb#202]
I wanted to open an issue re-persistence guarantees, since a commit on MacOS now guarantees consistency but not persistence. Would it make sense to introduce an additional commit type, something like `barrier_commit`, which calls `fcntl(F_BARRIERFSYNC)` on MacOS, but uses `self.inner.flush()` on other platforms,  and then change the normal commit to use either `self.inner.flush()` or `fcntl(F_FULLFSYNC)` on MacOS?

The idea being that the default commit on MacOS is slow but guarantees persistence, but you can use `barrier_commit`, if consistency is good enough.

**Comment by cberner** [comment]
Ya, I think this is a good idea. Instead of another commit method though, what do you think of adding a `set_durability()` method on `WriteTransaction` which takes an enum?

**Comment by casey** [comment]
That's a great idea, and non-durable commit can be folded into that as well. Maybe something like this?

```
enum Durability {
  None, // no guarantee of durability
  Eventual, // F_BARRIERSYNC or better, eventually durable, as long as you don't unplug your computer
  Immediate, // immediately durable after function returns
}
```

**Comment by cberner** [comment]
Yep, that's exactly what I had in mind. Do you want to implement it? If not, I'll probably get to it later this week
