### ISSUE TITLE
lmdb faster with large values

### ISSUE THREAD

**Issue by casey** [cberner/redb#204]
Ord is slowing down quite a bit after indexing around 150k blocks. This is different from the performance cliff we observed before, in that it still makes forward progress, it's just 5x slower than before. We're not sure this is due to redb, and we're planning to create a branch of ord that uses lmdb so we can do an apples to apples comparison, but in the meantime we benchmarked redb against lmdb with larger keys, and found that redb is 7x to 5x slower (7x on Liam's laptop, 5x on my laptop.)

I think this slowdown might not be captured in the existing benchmarks, so I wanted to open an issue for it. The code is in https://github.com/casey/redb-slowdown. Running on my machine:

redb: 5.57s user 15.25s system 69% cpu 29.899 total
lmdb: 0.42s user 3.50s system 65% cpu 5.950 total

I tried running the same benchmark with redb using non-durable commits, and with fsync instead of F_BARRIERFSYNC, which made it slightly faster, but didn't erase the gap completely.

**Comment by cberner** [comment]
How big are the keys & values that ord uses? That benchmark has large values, but small keys. I would expect redb to be slower than lmdb, although I'm not sure how much. lmdb I believe has an optimization to store large values out of band, which I haven't implemented yet, so in the current redb code you'll end up with worse write amplification because it keeps copying your large values around.
Large keys are even worse, because then there's a log factor in the number of times you need to make copies, when writing

**Comment by casey** [comment]
I didn't check, but these outputs were surely the result of consolidating multiple outputs whose inputs were fees. Blocks can have up to around 2.5k transactions, so a block reward output can receive ordinals for up to 2.5k discontinuous ranges. If you consolidate a few of these inputs, as miners are likely to do, you can get outputs with tons and tons of ordinal ranges in them.

**Comment by cberner** [comment]
Ah, got it. Ya, this just needs to be optimized in redb, so that it better handles the number of entries per page. This is related to the same code that's causing the fragmentation issues you saw with really small keys

**Comment by casey** [comment]
Gotcha, that makes sense. Maybe this also explained how it performed. It didn't become consistently slow, it would process a few blocks quickly, and then a slow block, and this didn't seem to have much to do with the number of transactions per block. Could this be explained by large-value write-amplification from some, but not all inserts?

**Comment by cberner** [comment]
Oh ya, totally. That sounds like every now and then you process a transaction that and the key sorts into the same page as a existing large value. It then has to do CoW and so copies the large value, which makes your insert slow even though the value you are writing may be small

**Comment by cberner** [comment]
@casey does this benchmark seem like it matches your workload? https://github.com/cberner/redb/tree/opt_large

At least on my machine it more or less matches lmdb:

```
redb: Bulk loaded 4000 2MB items and 1000000 small items in 12116ms
lmdb-rkv: Bulk loaded 4000 2MB items and 1000000 small items in 10530ms
```

**Comment by casey** [comment]
This should match our workload. We added LMDB as a second switchable backend, controlled by a feature switch, and the prod server is running with LMDB. I should figure out a way to benchmark on the same series of blocks to get an apples to apples comparison. The hard part is that it gets slow only after a few years of blocks, which take hours to get to, so benchmarking is hard.
