### ISSUE TITLE
Can't reopen table during transaction

### ISSUE THREAD

**Issue by casey** [cberner/redb#208]
I noticed that you can't open a table, drop it, and then reopen it during the same transaction. I ran into it because I was refactoring some transaction code, and I was in an intermediate state where the half the code was in one function, and the rest was in another function, and I was manipulating a table in both places. I wasn't able to open it in one function, close it, and then reopen it in another function. If this is easy to allow, it would be nice to do so.

**Comment by casey** [comment]
Whoops, fat-fingered the submit button. Fixed now.

**Comment by cberner** [comment]
Ah, I wondered if anyone was going to hit this when I added that restriction :stuck_out_tongue: Ya, this is pretty easy to fix
