### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by casey** [cberner/redb#215]
I'm debugging an issue where a redb database is very slow to open, and being able to turn on logging for redb would be nice, to get some insight into what it's doing.

**Comment by cberner** [comment]
Is there any logging functionality in the Rust standard library? It looks like I need to use the `log` crate, which I guess is ok, but I'm kinda proud of having only `libc` as a dependency :grin:

**Comment by casey** [comment]
There isn't, although the log crate is owned by the Rust project, so it's close to being official. But I actually don't need this anymore personally, so I wouldn't consider it high priority.
