### ISSUE TITLE
Post about redb

### ISSUE THREAD

**Issue by casey** [cberner/redb#218]
When do you think you'll start posting publicly about redb? I have a feeling that you'll get an enthusiastic response when you do, and might get valuable feedback on the design and API, as well as review of the trickier bits. I've posted about `just` to `r/rust` quite a few times over the years, and have gotten a ton of interest and users by doing so.

**Comment by cberner** [comment]
I'm not sure exactly, but hopefully "soon" :) The big thing I want to finish before doing that is the file format changes that I know I want to make, like #147 , and then it just needs some docs & cleanup

**Comment by casey** [comment]
The file format definitely doesn't have to be fully stable before posting about it, since breaking changes are expected from alpha software, although of course, no harm waiting if there are file format changes coming down the pipe soon.

**Comment by cberner** [comment]
https://www.reddit.com/r/rust/comments/uahh4y/redb_high_performance_embedded_keyvalue_database/?

**Comment by casey** [comment]
I'd suggest writing a blog post where you talk about the design of redb, and how it improves on other key-value stores for Rust, how it's related to LMDB, how it's fast, etc, and also posting the text as a top-level comment in that post.

**Comment by cberner** [comment]
Ya, I plan to do a blog post. Probably when it's closer to 1.0 though

**Comment by casey** [comment]
Short of a blog post, I think definitely a summary in the post as a top-level comment would be a good idea. Just summarizing why it's interesting, advantages and disadvantages, etc. Some people will probably bounce off the readme.
