### ISSUE TITLE
Removing a record using a non-exact key

### ISSUE THREAD

**Issue by casey** [cberner/redb#220]
Is there a way to remove a record `key0, value0` using a key, `key1`, which is the key immediately before or after `key0`, without doing multiple lookups? 

LMDB supports this with `Cursor::del`:

```rust
let mut cursor = lmdb_write_transaction.cursor(&database)?;
let mut access = lmdb_write_transaction.access();
cursor.seek_range_k::<[u8], [u8]>(&access, key)?;
cursor.del(&mut access, lmdb::del::Flags::empty())?;
```

For `redb` you have to do a get and then a remove, which requires two lookups:

```rust
let key = table.range(key..)?.next().unwrap().0.to_vec(); // conversion to owned value required to avoid borrow errors
table.remove(&key)?;
```

**Comment by cberner** [comment]
Not at the moment. I have a ticket open for implementing `pop_first` and `pop_last`: https://github.com/cberner/redb/issues/162 Is that what you need, or do you need to remove arbitrary keys?

One thing you can do to remove the `to_vec` is use two separate transactions. You should be able to have a read transaction that you use for the iterator, and then a write for the delete

**Comment by casey** [comment]
> Not at the moment. I have a ticket open for implementing `pop_first` and `pop_last`: #162 Is that what you need, or do you need to remove arbitrary keys?

The latter, the keys I need to remove could be anywhere in the table.

> One thing you can do to remove the `to_vec` is use two separate transactions. You should be able to have a read transaction that you use for the iterator, and then a write for the delete

That's true, if the to_vec winds up being slow I'll try that.

**Comment by cberner** [comment]
I see. How many do you do per transaction, and what's the case where ord does this?

**Comment by casey** [comment]
The table where we need to do this was too slow to maintain, so we're going to switch to a different strategy for the same purpose, so this isn't a pressing need anymore. This was for the table that maintains a record of where all ordinal ranges currently are.

**Comment by cberner** [comment]
Ok. Gonna close this for now then. I did a quick benchmark comparing a single call to `get(key)` vs doing two sequential calls to `get(key)` which I think sets an upper bound on how much this would improve performance. The difference was ~1.5x. I assume it's not 2x because after the first call everything is in the processor's cache. 1.5x only seems worth optimizing if this is a common pattern
