### ISSUE TITLE
Use write() instead of a writable mmap

### ISSUE THREAD

**Issue by cberner** [cberner/redb#256]
Mixing writes to mmap'ed memory with fsync, like we do on OSX, is probably not safe. Also, using write() and a read-only mmap would prevent accidental data corruption by errant unsafe code.

**Comment by casey** [comment]
Are there guarantees about the visibility of data written to a single file by multiple `write`s in the same thread, followed by an `fsync`? If so, could this be used to avoid a second fsync?

**Comment by casey** [comment]
Just thinking about it, it seems like there probably aren't any guarantees. Write calls happen in sequence,  but they'll terminate in a write to the page cache, and it would be pretty weird if the OS was tracking the last-update time of each page, so that it could flush them in sequence.

**Comment by cberner** [comment]
Ya, I'm pretty sure there are no guarantees about write ordering. Linux doesn't even have an API for write barriers, although OSX does have F_BARRIERFSYNC

**Comment by casey** [comment]
I wonder how `F_BARRIERFSYNC` is even implemented. Seems like they would have to maintain some kind of data structure on top of just the page cache, since they need to have ordering information for writes.

**Comment by cberner** [comment]
I think `F_BARRIERFSYNC` just guarantees that everything written before the call to fsync will be stored durably, before anything written after it, so it's only 1 bit of ordering data. The trickier thing seems like the fact that the page cache needs to be copy-on-write until that fsync completes, so that additional writes to a page that is waiting to flush are not included in the fsync.

**Comment by cberner** [comment]
Notes to self, mainly. I started on an implementation in [use_write](https://github.com/cberner/redb/tree/use_write). However, this turned out be more complicated. Write performance is ~2x slower for 2PC, and 4x slower for 1PC+C because it always has to rewrite branch pages due to the checksums changing. To get good performance, I'd probably need to implement a userspace cache of dirty pages and coalesce adjust page writes to reduce the number of `pwrite` calls -- lmdb does this and it seems pretty effective.
