### ISSUE TITLE
Dynamic Sizing/Capacity

### ISSUE THREAD

**Issue by brockelmore** [cberner/redb#264]
thanks for your work on this!

Curious if you have any thought on allowing for dynamic database sizes? 

`libmdbx` does this (see [here](https://gitflic.ru/project/erthink/libmdbx) (author is russian and was moved to a russian based competitor after start of Ukraine invasion)), and it provides a good UX from that perspective.

Documentation for their resizing: https://libmdbx.dqdkfa.ru/group__c__settings.html#ga79065e4f3c5fb2ad37a52b59224d583e

On a broader note, there are some other interesting ideas in there that may provide some further inspiration

**Comment by cberner** [comment]
Yep, sure have! redb already supports dynamic growth as the default, so it should start at ~1MB and then grow as data is inserted. It doesn't support shrinking or offline compaction, but I plan to add at least the latter (https://github.com/cberner/redb/issues/20)

Cool, thanks for the link to libmdbx. That looks like an interesting list of features to consider adding
