### ISSUE TITLE
DB file of  redb is so large

### ISSUE THREAD

**Issue by piaoger** [cberner/redb#272]
Just have a chance to run the benchmark and found the file size is so large. 

```
sled:    454 MB  ( 428 MB zip)
lmdb:  582 MB  ( 390 MB zip)
redb:  1.00 GB   (271 MB zip)
```

**Comment by cberner** [comment]
This is expected behavior at the moment. The usage should be similar to lmdb, but file growth is by powers of 2. If you change the max file size for the redb database to 583MB, you'll see that it still works.
