### ISSUE TITLE
Benchmarks should not test using the temporary directory

### ISSUE THREAD

**Issue by ecton** [cberner/redb#282]
I recently learned about `tmpfs` when doing my own benchmarks for a database I'm working on. On Linux, `/tmp` may actually be mounted as a special filesystem that is implemented by using virtual memory for all written files. This means that all sync operations will essentially be instant, since there is no actual persistence being performed.

This leads to much different performance characteristics. For example, here's the large_values_benchmark on my machine before and after changing the location of the benchmarks:

```
+------------------------+--------+--------+---------+
|                        | redb   | lmdb   | sled    |
+====================================================+
| bulk load (2MB values) | 4605ms | 5376ms | 33013ms |
+------------------------+--------+--------+---------+

+------------------------+---------+---------+----------+
|                        | redb    | lmdb    | sled     |
+=======================================================+
| bulk load (2MB values) | 15607ms | 29809ms | 132410ms |
+------------------------+---------+---------+----------+
```

It's quite a large performance difference, and while I didn't try updating and testing the remaining benchmarks, it seems like it highlights redb's impressive performance even more. Great work!

**Comment by cberner** [comment]
Thanks for pointing this out! Yes, it seems like Fedora and some other distros mount /tmp as a tmpfs by default. I'll move the temp files to the current directory

**Comment by cberner** [comment]
@ecton off-topic, but since you have experience with database I'd love your feedback on #309 , if you have time! I'm trying to stabilize the redb file format in preparation for a 1.0 release.
