### ISSUE TITLE
Iterate over all the elements in table. How?

### ISSUE THREAD

**Issue by numToStr** [cberner/redb#285]
Hi,

Thank you for making `redb`. I am really enjoying working with it, but I hit a wall when wanting to list all the elements in a table.
So, is there a way to list all the elements in a table? I know about [`range()`](https://docs.rs/redb/latest/redb/struct.ReadOnlyTable.html#method.range) method but it doesn't seem to implement `IntoIterator`.

**Comment by cberner** [comment]
Ya, unfortunately it can't implement `Iterator` due to lifetime requirements. The object that is returned has a `.next()` method; you need to call that

**Comment by cberner** [comment]
Ah yes, looking at this again, I think that might be possible. I'll see if I can do the same
