### ISSUE TITLE
Guard against concurrent access

### ISSUE THREAD

**Issue by casey** [cberner/redb#290]
Does redb guard against concurrent access of a single database by two redb clients?

We have a server with a long-running process accessing a redb database, and it's really easy for us, while debugging/testing/deploying, to re-launch the same process and access the same database. I assume this is unsafe/undefined behavior.

Would it be possible to guard against this using file locks? I.e. redb clients try to acquire a file lock, and return an error if they can't. This wouldn't guard against arbitrary concurrent access, i.e. processes other than redb, but I think would cover the most common case.

**Comment by cberner** [comment]
Nope, not at the moment. I think this is a good idea though!

**Comment by casey** [comment]
Nice!
