### ISSUE TITLE
Table::get_mut

### ISSUE THREAD

**Issue by bonsairobo** [cberner/redb#291]
I don't think anything like this exists yet.

**Comment by bonsairobo** [comment]
Actually I guess `Table::insert_reserve` is kind of close, in that it at least lets the user avoid a redundant allocation if they can write directly into the resereved buffer.

But `AccessGuardMut` is private so it's pretty hard to use this feature.

**Comment by cberner** [comment]
What's the use case that you have? I thought of adding this, but it doesn't improve on the performance of `insert()` very much. Because redb uses copy-on-write storage, even `get_mut` would have to perform an allocation to store the new value

**Comment by bonsairobo** [comment]
That makes sense. Turns out I actually only need `insert_reserve` for what I'm trying to do.
