### ISSUE TITLE
Entered unreachable code

### ISSUE THREAD

**Issue by casey** [cberner/redb#293]
While removing LMDB in favor of redb, I think I found a bug. I didn't create a minimal repro, but I pushed it to a branch of ord so you can see it fail on CI:

https://github.com/casey/ord/runs/7398917442?check_suite_focus=true

**Comment by cberner** [comment]
Uh oh, that usually means the database has become corrupted :grimacing:  I'll take a look

**Comment by cberner** [comment]
Ah, this was a known issue that I fixed on master and forgot to release. Try version 0.3.0. I think you'll need to increase your redb database size, or increase the [commit frequency here](https://github.com/casey/ord/blob/5dd499a45fda996e80e53e63c9a3798c85395245/src/index.rs#L114) otherwise the database runs out of space.

**Comment by casey** [comment]
> Ah, this was a known issue that I fixed on master and forgot to release. Try version 0.3.0.

Nice, updated to redb 0.3.0 and it seems to be working.

> I think you'll need to increase your redb database size, or increase the commit frequency here otherwise the database runs out of space.

Does does resizing only happen on commit?

**Comment by cberner** [comment]
Hmm, no resizing should happen on any write. Which makes me wonder if there's a bug that prevents it from reusing pages that get used and then freed during a single write transaction. I just added a test for it though, and it seems to be working fine. Are you mixing any non-durable commits with your durable commits?

**Comment by casey** [comment]
Nope, all durable commits.

**Comment by cberner** [comment]
Ok, that sounds like a bug then. I'll take a look. I bet there is some case where a write transaction can't reuse a page that it has already dirtied

**Comment by casey** [comment]
Nice, I'll upgrade!
