### ISSUE TITLE
`fsync()` when opening a database

### ISSUE THREAD

**Issue by DemiMarie** [cberner/redb#299]
When `fsync()` fails, the on-disk state of a filesystem is largely undefined.  It is quite possible for the on-disk and in-memory state to be inconsistent, for example.  From what I can tell from reading papers (such as <https://research.cs.wisc.edu/adsl/Publications/cuttlefs-tos21.pdf>) the only safe approach is:

- `fsync()` at _open_ time, to prevent reading potentially-stale page-cache data.  If this fails, refuse to open the database.
- if any `fsync()`, `write()`, or `close()` fails, invalidate the entire database connection and fail all future I/O on it.

Note that `ENOSPC` can be a transient failure, if the underlying storage is thinly provisioned.  Therefore, it needs to be treated as equivalent to `EIO`.

**Comment by cberner** [comment]
Good to know, thanks! I'll fix this :)

**Comment by DemiMarie** [comment]
You’re welcome!  I suggest calling `fsync()` on the file descriptor immediately after `open(2)`.  It might also be necessary to `fsync()` the containing directory; it is after creating a file, for example.
