### ISSUE TITLE
Cannot compile on 32-bit platform

### ISSUE THREAD

**Issue by lthiery** [cberner/redb#302]
The following line causes a compilation error: https://github.com/cberner/redb/blob/7762a6e6f65a7823e6780ae99fbbb799a7374b82/src/tree_store/page_store/page_manager.rs#L49

```
error[E0080]: erroneous constant used
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.3.1/src/tree_store/page_store/page_manager.rs:461:63
    |
461 |             let region_size = requested_region_size.unwrap_or(MAX_USABLE_REGION_SPACE);
    |                                                               ^^^^^^^^^^^^^^^^^^^^^^^ referenced constant has errors
```

`usize` on this platform is 32-bits, so there's an overflow by 1. A naive fix is to change this type to u64, but I'm unsure if this has further implications, so I wanted to raise the issue. 

Generally, is redb suitable for 32-bit platforms?

**Comment by cberner** [comment]
It should be fine to reduce that to 2GiB or even less. I don't know whether it will work on a 32-bit platform, and I don't have access to one unfortunately. I would guess that it will work, but since redb relies on mmap, you'll be limited to fairly small databases
