### ISSUE TITLE
Better assert messages

### ISSUE THREAD

**Issue by casey** [cberner/redb#330]
This was totally my fault, but I hit these asserts:

```
assert_eq!(metadata.primary_slot().get_version(), FILE_FORMAT_VERSION);
assert_eq!(metadata.secondary_slot().get_version(), FILE_FORMAT_VERSION);
```

And got this error message:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `102`,
 right: `103`', /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.5.0/src/tree_store/page_store/page_manager.rs:613:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think these kinds of errors, e.g., somehow opening a bad file, opening a database that has been corrupted, etc. Will not be uncommon, so it might be good to include better error messages.

One option would just be to add a format string to the asserts:

```
assert_eq!(metadata.primary_slot().get_version(), FILE_FORMAT_VERSION, "Bad primary slot file format: {} (current is {}", metadata.primary_slot().get_version(), FILE_FORMAT_VERSION);
assert_eq!(metadata.secondary_slot().get_version(), FILE_FORMAT_VERSION);
assert_eq!(metadata.primary_slot().get_version(), FILE_FORMAT_VERSION, "Bad secondary slot file format: {} (current is {}", metadata.secondary_slot().get_version(), FILE_FORMAT_VERSION);
```

Another option would be to add something like this:

```
enum Error {
  Corruption(String)
}
```

Which then prints out `database corrupted or invalid: {message}`.

An error might be a bit friendlier, since the application might be able to continue. However, errors don't natively include backtraces, and an assert will print a backtrace.

**Comment by cberner** [comment]
Turns out I already had that enum variant, and just wasn't using it =)
