### ISSUE TITLE
MAX_USABLE_REGION_SPACE and target_pointer_width database portability

### ISSUE THREAD

**Issue by casey** [cberner/redb#332]
I forgot what the region size was, so I was looking at the MAX_USABLE_REGION_SPACE constant.

I noticed that it's different on 32 and 64 bit platforms, which made me wonder: What happens when a redb database is created in a 32 bit platform, and then opened on a 64 bit platform, and vice versa?

I think the ideal scenario might be for each redb database to record whether it's a 32 bit database or a 64 bit database. Then:

- 64 bit databases are created on 64 bit systems by default
- 32 bit databases are created on 32 bit systems by default
- 64 bit systems can open 32 and 64 bit databases
- 32 bit systems can open 32 bit databases, but get an error when trying to open 64 bit databases

Other options:

- Always create 32 bit databases, for portability, and require specifically requesting a 64 bit database
- Storing instead the max region size, instead of the bit target

Also, I may have entirely misunderstood the `MAX_USABLE_REGION_SPACE` constant, since it seems possible that regions might still be allocated as 4GiB on all systems, and only that keys are limited to 128MiB on 32 bit systems.

**Comment by cberner** [comment]
Oh ya, I should really rename that constant. It's actually the **default** max region size, and the user can even change it when creating the database by using `DatabaseBuilder::set_region_size`. The max region size is then [stored in the database file](https://github.com/cberner/redb/blob/43043c4421ef74464be77d6b072c973c1cefaed5/src/tree_store/page_store/page_manager.rs#L28). So it should already work that way: databases are portable between 32bit & 64bit. 
I haven't tested on 32bit, so there are probably bugs, but in theory the only reason to get an error is if you have set the maximum db size to be larger than the available virtual address space.

**Comment by casey** [comment]
Ah, interesting. So the only factor in whether or not the database will work on a system (regardless of pointer size) is whether or not the database can be mapped, i.e. whether or not it will fit in available address space?

In that case I'm not sure I understand why the default max region size is different on 32 bit and 64 bit systems. On a 32 bit system you already have to set a small max database size which would implicitly limit the max region size.

**Comment by cberner** [comment]
Oh, the main reason is because there was a compilation error: https://github.com/cberner/redb/issues/302

Then I reduced it to 128MiB, because I figured on a 32bit OS it's unlikely that someone would be storing values > 128MiB

**Comment by casey** [comment]
Ah, interesting. Could it be:

```
const MAX_USABLE_REGION_SPACE: usize = 4 * 1024 * 1024 * 1024 - 1;
```

On all platforms, so that that aspect of behavior doesn't differ between 32bit and 64bit system. Also, if there's already overhead that prevents the full 4GiB from being used on all platforms, then the lost byte doesn't seem that consequential.

It's definitely unlikely that someone would be storing values > 128MiB on a 32bit system, but since they're already constrained by the max database size, but they can at least try.

**Comment by casey** [comment]
Also, apparently there's [this thing](https://en.wikipedia.org/wiki/Physical_Address_Extension), which I find quite confusing, but which seems to indicate that you might sometimes have more memory than 4GiB on a 32 bit system.

**Comment by cberner** [comment]
It has to be a multiple of the page size, and should really be a power of 2 since a tree allocator is used. I just [merged a change](https://github.com/cberner/redb/pull/333/files) to the file format that changes the value stored in the file to be the number of pages. I didn't change that constant yet, but I now could so that it doesn't overflow.

Note that this is just a default and not the actual max size. If you want to store values > 128MiB on 32bit, you totally can. You'll just need to set a bigger value with `set_region_size`.

**Comment by cberner** [comment]
Hmm, I don't know much about PAE, but it sounds like it just allows the OS to run multiple processes that each use different physical address ranges, and the physical address space can exceed 4GiB. I don't think it allows a single process to access more than 4GiB:

> The 32-bit size of the virtual address is not changed, so regular application software continues to use instructions with 32-bit addresses and (in a [flat memory model](https://en.wikipedia.org/wiki/Flat_memory_model)) is limited to 4 gigabytes of virtual address space

**Comment by casey** [comment]
> The 32-bit size of the virtual address is not changed, so regular application software continues to use instructions with 32-bit addresses and (in a [flat memory model](https://en.wikipedia.org/wiki/Flat_memory_model)) is limited to 4 gigabytes of virtual address space

Gotcha. That does mean on such a system that each process might see 4GiB, and so be able to map large values without issue, so 128 MiB might be too small, so maybe 2 GiB is a good default on 32 bit systems?

**Comment by casey** [comment]
I think the reason it makes me nervous to have it be configurable between systems is that users might find it surprising if it changes between OSs. Another option is to make the default 2GiB on both 32 and 64 bit systems. That might also have the benefit that on 64bit systems, you wouldn't expect to be able to create 4GiB values but fail, due to overhead, which might be surprising.

**Comment by cberner** [comment]
Ya, that's a reasonable concern. I think the best thing to do is to change that to a `u64` so that it's pointer width independent. Probably not a priority right now though, since thinking through 32bit platforms I realize there are a bunch of bugs that are going to break it. Like this going to overflow: https://github.com/cberner/redb/blob/30e9af7358328ea18c5efbcf9df069e996405609/src/tree_store/page_store/page_manager.rs#L124

**Comment by casey** [comment]
Ah, gotcha. I think that for a codebase like this, which is so sensitive to integer overflow and truncation, as conversions should probably be banned with [this clippy lint](https://rust-lang.github.io/rust-clippy//master/index.html#as_conversions), and replaced with `.into()` for infallible conversions, and `.try_into().unwrap()`, which will at least panic if there's an issue, instead of silently truncating like `as` does.

I would definitely check out all the other pedantic clippy lints, there's some good stuff in there.
