### ISSUE TITLE
Checkpoints and rollbacks

### ISSUE THREAD

**Issue by casey** [cberner/redb#341]
The main [ord](https://github.com/casey/ord) instance at [ordinals.com](https://ordinals.com) is now running redb, and I'm starting to think about how to deal with reorgs of the bitcoin blockchain.

We have a few tables, and will probably wind up with a few more, and it would be super convenient if redb supported checkpoints and rollbacks directly. We could keep checkpoints of the last 6 blocks (reorgs larger than a block or two are extremely rare, and reorgs of 6 blocks or more have never happened outside of a couple instances due to bugs) and upon detecting a reorg, roll back to the state before the orphaned block, and continue as normal. The alternative, which isn't actually that hard, is to figure out which transactions and blocks we need to purge from the database, but will be tricky, and could be a source of bugs if we don't get the rollback logic correct for each table.

Are checkpoints something that redb could support easily? E.g. instead of having two db roots and ping-ponging between them, have N db roots, configurable per database, and cycling through them every commit, or having some kind of explicit way of designating that a commit should be a checkpoint.

**Comment by cberner** [comment]
Ya, that's fairly straight forward, and is similar to the #271 issue I have filed already. The main thing I'll need to think through is the performance aspects: either the rollback will take time linear in the amount of data in the database, or the checkpoints will require space linear in the number of writes that occur after them. Restoring the data is easy, and doesn't even require n-buffered db roots -- the checkpoint object can just store the db root. However, all the allocator state in the database will have to be rolled back, which means undoing every allocator that occurs after the checkpoint is taken.

**Comment by casey** [comment]
I think for ord the best thing would be that checkpoints require space linear in the number of writes that occur after them. We have one write transaction per block, and with six checkpoints, we'd have a maximum of five writes after a checkpoint. Our database is big, and will get bigger.

What would nested writes do? Having a write transaction pending, and then doing another write transaction within it?

**Comment by cberner** [comment]
It's linear in the number of insertions/deletions, not the number of transactions, but ya that still seems better.

Ya, the idea is that you can abort part of your transaction and continue with the rest of it. I'm not sure how useful it is, but it seems easy enough to support, and LMDB has them :)

**Comment by cberner** [comment]
@casey I thought of a simpler and hopefully better implementation, which is to just save a complete copy of the allocator state in the checkpoint. How would you feel about checkpoint objects that consume ~64kb of RAM per 1GB of data in the database?

**Comment by casey** [comment]
@cberner That sounds totally reasonable to me. 64KiB * 6 checkpoints * 100 GiB (we're at 50 GB but giving some headroom) is 37.5 MiB RAM, which sounds pretty reasonable.

How does it work? I guess it needs to consult all checkpoint allocators states before freeing old pages?

**Comment by cberner** [comment]
Actually it's even easier than that. It doesn't free any pages that can be referenced by a checkpoint, just like when a read transaction is open. As an aside, I think I'm going to name them "savepoints" which seems to be a common term among SQL databases. So you have the invariant that any page which was allocated when the savepoint was created will still be allocated and have the same data. Therefore to rollback to the savepoint all you need to do is restore the root pointers to the old value, and then free any pages that were allocated after the savepoint was created. The latter is trivial to do by keeping a complete copy of the allocator state and restoring it

**Comment by casey** [comment]
Dope, that sounds good to me.

**Comment by casey** [comment]
Is savepoint more common than checkpoint? I was just doing some google searches, and "sql checkpoint" had more search results than "sql savepoint".

**Comment by cberner** [comment]
checkpoint is probably more common, but it means something different I think. SqlServer [says that a checkpoint](https://learn.microsoft.com/en-us/sql/relational-databases/logs/database-checkpoints-sql-server?view=sql-server-ver16) is a "known good point from which the SQL Server Database Engine can start applying changes contained in the log during recovery after an unexpected shutdown or crash", so basically it's a compaction of the WAL is how I read it. However, there's no way for the user to rollback to a checkpoint.

Whereas a [savepoint saves the state of a transaction](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/save-transaction-transact-sql?view=sql-server-ver16) with a user defined name, so that the user can [later rollback](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/rollback-transaction-transact-sql?view=sql-server-ver16) the transaction to that point

**Comment by casey** [comment]
Ah, okay, I guess using the accepted database terminology is reasonable. And, it looks like PostgreSQL agrees:

https://www.postgresql.org/docs/current/sql-checkpoint.html
https://www.postgresql.org/docs/current/sql-savepoint.html
