### ISSUE TITLE
Is database file contents deterministic?

### ISSUE THREAD

**Issue by casey** [cberner/redb#349]
If you create two different redb databases and perform the same sequence of inserts and deletions, will the two files be byte-for-byte the same?

If not, it might be nice to try to guarantee that they will be the same. We recently did a bunch of optimization work on `ord`, and it looked like the same operations could produce `index.redb` that contained the same keys and values, but which were not byte-for-byte identical. If they were identical, we could have done a byte-wise comparison of the before- and after-optimization databases, to ensure that the same databases were produced.

**Comment by cberner** [comment]
yes, I think it should be. There's no sources of randomness used. At least at the moment though, there are some additional things you would need to do for it to be exactly identical:
1. group them into the same transactions
2. order any read transactions the same way (reads allocate a transaction id at the moment)
3. ensure that they go through the same crash recovery, or always shut down redb cleanly: ensure `drop` is called on the `Database`.

**Comment by casey** [comment]
Gotcha. In that case we wouldn't have gotten the exact same contents, because we changed the way writes are batched, but good to know for the future.

**Comment by cberner** [comment]
Ah, ya that's never going to produce bitwise identical files then. Page garbage collection happens when you commit a transaction, so changing that will change the pages that data gets allocated into
