### ISSUE TITLE
Remove usage of `as X` for X < 64, including `as usize`

### ISSUE THREAD

**Issue by cberner** [cberner/redb#362]
This should be banned by the regex in the CI too, because it could silently truncate values.

**Comment by casey** [comment]
You can do this with the [`as_conversions` lint](https://rust-lang.github.io/rust-clippy/master/#as_conversions).

**Comment by cberner** [comment]
Looks like there's a list of sublints that cover just the lossy cases:
* cast_possible_truncation
* cast_possible_wrap
* cast_precision_loss
* cast_sign_loss

**Comment by ever0de** [comment]
I'm working on this, and I have a question.
If `try_into` is used for type conversion, it seems that the return type should be wrapped in `Result` for a function that had no possibility of failure in the past.
Is it better to convert this? Or leave it as `unwrap` or `expect`?

**Comment by cberner** [comment]
Cool, thanks for working on it!

Yes, `try_into().unwrap()` seems like the right thing. There might be a few cases where propagating the error makes sense, but I would guess it doesn't in the majority of cases.

> +do you turn clippy into warn? or deny, forbid?

It should be Clippy `deny`.

A couple other pointers for working on this:
1. In many (most?) cases the right thing to do is to change variables from `usize` into either `u64` or `u32`, rather than adding `try_into()`. For example [this](https://github.com/cberner/redb/blob/69c8f776b9c9da099377a8b408b7998c5432ec4d/src/tree_store/page_store/page_manager.rs#L1404) `page_size` variable should be a `u32` since that's what's stored in the file format
2. The xxh3.rs file is vendored from here: https://github.com/cberner/xxh3 so you should submit the changes there first and then copy the new file over
3. It'll be easiest for me to review your changes if you submit a series of PRs that touch only a few files and keep the changes to 100 lines or so. That'll help get them merged quickly so that you don't hit too many merge conflicts with other changes

**Comment by ever0de** [comment]
Thanks for the detailed explanation,
I'll wrap it up and post a PR.

**Comment by ever0de** [comment]
<https://github.com/cberner/xxh3/pull/1> Submitted a pull request to `xxh3`.
