### ISSUE TITLE
Multi-threaded fuzzing

### ISSUE THREAD

**Issue by casey** [cberner/redb#374]
Does `redb` have multi-threaded fuzzing? I think some kind of parallel fuzzing would have uncovered #370. It would be pretty simple to simulate redb's MVCC model manually.

**Comment by cberner** [comment]
Nope, but ya that'd be great to have

**Comment by casey** [comment]
Nice! Did the multi-threaded fuzzer find the bug you fixed in https://github.com/cberner/redb/pull/388/commits/9dc9cb0b92d8fd3f6301dcae5996987b1a63ed90?

**Comment by cberner** [comment]
yep, it sure did! :)
