### ISSUE TITLE
Should processes block each other?

### ISSUE THREAD

**Issue by casey** [cberner/redb#376]
This struck me while doing the rwlock stuff: If multiple processes open a redb database, perhaps they should just block each other, instead of panicking.

**Comment by cberner** [comment]
I don't think so, but do you have a use case in mind?

My thinking is that with transactions & threads they're all inside your application, so you can expect them to complete eventually. However, with another process there's no way to know if it will terminate, so blocking could deadlock. If you do in fact want blocking then you can just spin & sleep trying to open the file. It doesn't panic it just returns `Err(DatabaseAlreadyOpen)`

**Comment by casey** [comment]
> I don't think so, but do you have a use case in mind?

Yeah, just the way that ord uses the index. There are multiple subcommands that open the index, check something, close the index, and return. It would be nice if when those are run at the same time, they just blocked each other. I could implement a spin lock, but if it's a feature of the file locks that redb is using, then that might be a cleaner solution.

One option to prevent accidental deadlocks would be to set a timeout when you opened the database. If no timeout it set, the default, you get the current behavior. If you set a timeout, you block for that timeout.

**Comment by cberner** [comment]
I looked into the file lock API and there's no easy way to set a timeout. Would you want a bool for blocking/non-blocking?

**Comment by casey** [comment]
Hmm, interesting. I'm not sure in that case. If the ord server were running, and you performed a wallet operation, blocking forever since the server is running in the background might just be confusing. So maybe I wouldn't actually wind up using a bool block/non-blocking setting. If we only had short-lived wallet operations, then I would definitely a bool. So maybe this shouldn't be implemented until someone has a strong need for it.

**Comment by cberner** [comment]
k. Ya, this seems application specific enough that it's probably best if you implement your own spin wait with a timeout
