### ISSUE TITLE
MultimapValueIter is hidden from docs

### ISSUE THREAD

**Issue by casey** [cberner/redb#396]
I noticed that MultimapValueIter has `#[doc(hidden)]`. Is this intentional? I was looking it up today to try to figure out what methods it had, and couldn't find it in the docs.

**Comment by cberner** [comment]
Kind of. I was actually going to ask you about this. What's best practice for returning iterator types? It's marked hidden because I was thinking of changing the return type to `impl Iterator<Item = ...>` that way I could rename the struct without breaking the public API.

**Comment by casey** [comment]
In general, I think that `#[doc(hidden)]` is only for things that users will never, or should never interact with directly For example, things that are only used by macros that you provide, or used in tests and benchmarks but are otherwise perma-unstable. So in this case, because it's the return type of a public function, it shouldn't be hidden, since that leaves a weird dangling reference in the docs of the function that returns it. I might also not use `impl Iterator`. I'm not a huge fan of `impl Iterator` in the return-type position, since it means that it isn't possible to save the iterator to, for example, a struct field, without boxing it.
