### ISSUE TITLE
Multimap value order

### ISSUE THREAD

**Issue by casey** [cberner/redb#397]
Are there any guarantees about what order multimap values are returned in?

**Comment by cberner** [comment]
Currently they're returned in ascending order. That's very likely to become a guarantee, but since it's an implementation detail, I'm waiting to document it until the file format is stable

**Comment by casey** [comment]
Dope, that's very convenient for me, so if that becomes a guarantee it would be great.

**Comment by casey** [comment]
Whoops, hit close, but maybe this should be left open until it's guaranteed, or not.

**Comment by casey** [comment]
Nice!
