### ISSUE TITLE
[Questions] Usage

### ISSUE THREAD

**Issue by The-Mr-L** [cberner/redb#404]
hi :) first of thank you for sharing, it is great. 

So, what I understand from reading the issue tracker  is that it should be supported to have the db resize itself if out of space right? but how do you enable it?  I get out of space errors in my tests. I just init the db with 1MB as the db_size but it seems to be fixed max size or what?

2. Are you using this in some projects of your own at this point, or is it still a no go ;) 

3. more general question how well would a kv store like this be for image storage for example to backup images would I gain some speed using a higher page size compared to to just using the os filesystem. I just wonder if it would make backup lots of images go faster. Like in this way there is potential fever system calls or am I completely wrong?   

thanks again

**Comment by cberner** [comment]
Ah yes, that's the maximum size. So you should set that to the max size you want, and it will start out at a much smaller size and grow dynamically.

2) it's still very beta, but yes I'm using it in one project: https://github.com/fleetfs/fleetfs
3) it shouldn't matter very much, but if you really care about performance you may want to try a larger size and benchmark it. The testing I've done shows that there is at most a 20% difference or so

**Comment by The-Mr-L** [comment]
when I do set the db_sze to 10GB then it creates a 10GB empty file, is that expected? I am on windows 10 64bit

**Comment by cberner** [comment]
Ah, unfortunately dynamic growth is not supported on Windows. The person who contributed the Windows support explained a bit about why it is difficult: https://github.com/cberner/redb/pull/369

**Comment by The-Mr-L** [comment]
gotya, thank you :)
