### ISSUE TITLE
Crash writing to a large DB

### ISSUE THREAD

**Issue by bruwozniak** [cberner/redb#412]
I have a DB that's basically a large MultiMap of  `[u8; 20]` keys and `[u8; 32]` values. Inserting this in batch transactions of 100K keys, the DB crashes around 123GB of on-disk size (max size configured to 1TB):

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', /Users/bruno/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.8.0/src/tree_store/btree_base.rs:983:60```

**Comment by bruwozniak** [comment]
I did not configure custom page size nor region size.
I can't get the backtrace to show anything meaningful sadly, it's a bunch of memory addresses and `_libc_thread` at the bottom, even though I made sure to build it with debug symbols.

**Comment by cberner** [comment]
Huh, that's odd. Ok, I'll see if I can debug this anyway. When you say that it's "basically a large MultiMap". You mean that it's a `redb::MultimapTable` right?

**Comment by bruwozniak** [comment]
@cberner yes, that's what I mean.

**Comment by cberner** [comment]
Are you able to reproduce this? I have a theory of what is happening, but it doesn't really make sense given that you didn't set a custom page size. So I'd like to create a debug branch for you to try running to collecting some more debug info

**Comment by casey** [comment]
Is this happening on a mac? In which case the page size is might 16k, instead of the 4k default.

**Comment by bruwozniak** [comment]
No, this was on Linux. (specifically aarch64, ARM instance on AWS)

**Comment by bruwozniak** [comment]
@cberner for the moment I had to switch to LMDB to finish a project, so I am not sure I will be able to reproduce this again on a branch quickly.
I confirmed that pagesize on the system is 4K:
```
$ getconf PAGE_SIZE
4096
```
