### ISSUE TITLE
Test with Alice

### ISSUE THREAD

**Issue by Kerollmops** [cberner/redb#417]
Have heard about Alice to test the database? I don't know much about it, but maybe [this issue can be interesting to you](https://github.com/spacejam/sled/issues/83).

**Comment by cberner** [comment]
I have ya, although I've never used it. Unfortunately it doesn't support mmap'ed writes, which redb relies on, and it hasn't been updated in 8yrs so I'm guessing it's unsupported

**Comment by cberner** [comment]
Closing, but lemme know if you find something similar that looks more supported!
