### ISSUE TITLE
Hard to reproduce panic in redb-0.8.0/src/tree_store/btree_base.rs:983

### ISSUE THREAD

**Issue by VirtuallyThere** [cberner/redb#422]
When I run the `ord index` command from https://github.com/casey/ord on a Mac, starting from a non-existent index, I got a panic twice. The problem has been elusive to reproducing, however. Here's the error message:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', /Users/uc/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.8.0/src/tree_store/btree_base.rs:983:60
```

See https://github.com/casey/ord/issues/752 for a little more info.

**Comment by VirtuallyThere** [comment]
This seems to be the same panic as #412

**Comment by cberner** [comment]
Ya, that definitely looks like the same panic. I have a Mac that I can try reproducing this on. What are the exact steps that you followed? Just run `bitcoind` and then `ord index`? Did you interrupt the indexing at all, or just let it run until it crashed?

**Comment by VirtuallyThere** [comment]
I just ran `ord index` from a clean data directory (so that there was no existing `index.redb`), and let it run until it crashed, no interruptions. The times when it crashed, it was in blocks below 250k, so got to the crash fairly fast.

Here's the command I used:

```
target/release/ord --height-limit 500000 --cookie-file /path/to/bitcoin/data/.cookie --data-dir data index
```

**Comment by cberner** [comment]
Thanks. I've been able to reproduce the crash on Linux by forcing ord to always use 16k pages. You're right about it being hard to repro though. It's taking ages and seems to go away when I enable backtraces :/

**Comment by VirtuallyThere** [comment]
Awesome, thank you!
