### ISSUE TITLE
Tuple type lifetime issue

### ISSUE THREAD

**Issue by casey** [cberner/redb#431]
I think there's an issue with tuple type lifetimes.

Check out the code in #430. I added a new test which tries to insert a `&str` borrowed from a `String` into a table:

```rust
#[test]
fn tuple_type_lifetime() {
    let tmpfile: NamedTempFile = NamedTempFile::new().unwrap();
    let db = unsafe { Database::create(tmpfile.path(), 1024 * 1024).unwrap() };

    let table_def: TableDefinition<(&str, u8), (u16, u32)> = TableDefinition::new("table");

    let write_txn = db.begin_write().unwrap();
    {
        let mut table = write_txn.open_table(table_def).unwrap();
        table
            .insert(&(String::from("hello").as_str(), 5), &(0, 123))
            .unwrap();
    }
    write_txn.commit().unwrap();

    let read_txn = db.begin_read().unwrap();
    let table = read_txn.open_table(table_def).unwrap();
    assert_eq!(table.get(&("hello", 5)).unwrap().unwrap(), (0, 123));
}
```

It fails with:

```
error[E0716]: temporary value dropped while borrowed
   --> tests/basic_tests.rs:132:23
    |
132 |             .insert(&(String::from("hello").as_str(), 5), &(0, 123))
    |                       ^^^^^^^^^^^^^^^^^^^^^ creates a temporary which is freed while still in use
133 |             .unwrap();
    |                      - temporary value is freed at the end of this statement
134 |     }
    |     - borrow might be used here, when `table` is dropped and runs the `Drop` code for type `Table`
    |
    = note: consider using a `let` binding to create a longer lived value
```

It looks like the `&str` is getting some lifetime that isn't compatible with the lifetime of the temporary, and thus can't take a str borrowed from the temporary.

**Comment by casey** [comment]
I added a couple of additional functions which demonstrate what is probably the same issue, but in the actual context where I ran into it, but which have more explicit error messages:

```rust
#[test]
fn tuple_type_function_lifetime() {
    fn insert_inferred_lifetime(table: &mut redb::Table<(&str, u8), u64>) {
        table
            .insert(&(String::from("hello").as_str(), 8), &1)
            .unwrap();
    }

    fn insert_explicit_lifetime<'a>(table: &mut redb::Table<(&'a str, u8), u64>) {
        table
            .insert(&(String::from("hello").as_str(), 8), &1)
            .unwrap();
    }
}
```

**Comment by casey** [comment]
This worked with string literals because they have lifetime `'static`, which satisfies all other lifetimes.

**Comment by cberner** [comment]
Ah yes, interesting. I think this happens with any `&str` type, even without the tuple. I guess it makes sense too, because the `Table` contains the lifetime as part of its type. I guess the right thing to do is to implement `RedbValue` for `String` instead of `&str` and then you can use a `String` in the tuples. What do you think?

**Comment by casey** [comment]
That would be unfortunate, since it would mean that gets would always allocate. Could values define an associated type which would be used as the type passed to insert?

```
trait Value {
  type InsertValue<'a>;
}

impl Value for &str {
  type InsertValue<'a> = &'a str;
}

impl<T0: Value, T1: Value> Value for (T0, T1) {
    type InsertValue<'a> = &'a (T0::InsertValue, T1::InsertValue);
}

impl Value for u64 {
  // for cheap value types not sure if you would want to do this:
  type InsertValue<'a> = u64;
  // or this:
  type InsertValue<'a> = &'a u64;
}
```

**Comment by cberner** [comment]
There's already an associated type for the return values, so I think `get` could still be zero-copy for `String`. Oh ya, another associated type for the insert type might work. I'm not quite sure all the lifetimes would work out, but will give it a try once I finish up this file format change I'm working on

**Comment by cberner** [comment]
Is this line going to work? `type InsertValue<'a> = &'a (T0::InsertValue, T1::InsertValue);` Since `InsertValue` is a GAT, it seems like it would also have to take the lifetime `'a`, but then all the elements of the tuple will have the same lifetime

**Comment by casey** [comment]
I think I omitted a lifetime:

```
type InsertValue<'a> = &'a (T0::InsertValue<'a>, T1::InsertValue<'a>);
```

I think that all the elements having the same lifetime is fine, since it only requires that they live longer than `'a`, not have the exact same lifetime.

**Comment by cberner** [comment]
Oh, great!
