### ISSUE TITLE
Can `range` be made infallible?

### ISSUE THREAD

**Issue by casey** [cberner/redb#445]
I was looking at the `range` methods, and they return a `Result`, even though it looks like they can't fail. Could these be made infallible? If they can be made infallible, then tables might be able to implement `IntoIterator`.

**Comment by cberner** [comment]
Maybe. However, there is [this TODO](https://github.com/cberner/redb/blob/52c3b481daa3c26a42673e3e91c01147a7a8ab8b/src/tree_store/page_store/mmap.rs#L154-L156) and if I propagate that error then `range` and `get` will both be able to fail. There might be a different way to handle those fsync errors though. I haven't thought it through yet.

**Comment by casey** [comment]
Interesting. What about only returning such errors on commit or abort? Also, could more API errors be deferred until commit/abort, e.g. read/write transaction methods? If it's a viable strategy it might be worth thinking about applying more broadly.

**Comment by cberner** [comment]
Ya, that seems like it might work. I just don't know what the semantics of a failed fsync are

**Comment by casey** [comment]
> I just don't know what the semantics of a failed fsync are

That's a really interesting question. I would assume that data just wasn't flushed, and you can continue. Are you thinking that maybe some other invariants might not longer hold, and it's not safe to continue?

**Comment by cberner** [comment]
Ya, that's what I would hope too. I'm mainly wondering whether there are any cases that could lead to undefined behavior. There's a paper linked in [this issue](https://github.com/cberner/redb/issues/299) that I've only skimmed so far, but my take away was that error handling with filesystems is surprisingly tricky to get right.

**Comment by casey** [comment]
Reading that paper. What a bloodbath:

> For example, all three file systems mark pages clean after fsync fails, rendering techniques such as application-level retry ineffective. However, the content in said clean pages varies depending on the file system; ext4 and XFS contain the latest
copy in memory, while Btrfs reverts to the previous consistent state.

Does mean that on btrfs, you would technically need to just abort the process if you tried to fsync with any outstanding references to the map, to avoid undefined behavior?

Also, since the pages are marked clean, if they're evicted from the page cache, and you re-read data, you would then get stale data from disk.

> Failure reporting is varied across file systems; for example, ext4 data mode does not report an fsync failure immediately
in some cases, instead (oddly) failing the subsequent call.

> Some applications (Redis) are surprisingly careless with fsync, not even checking its return code before returning
success to the application-level update; the result is a database with old, corrupt, or missing keys.

> Other applications (LMDB) exhibit false-failure reporting, returning an error to users even though
on-disk state is correct.

**Comment by cberner** [comment]
Wow, that is incredibly broken. If I understand correctly, you must assume that when fsync fails the page cache of all ranges written since the last successful fsync are poisoned, and reading them results in an undefined value :exploding_head: 

I'm pretty sure this means the 1PC+C strategy won't work, because if fsync can flush some blocks but rollback others it could flush the transaction block but rollback some/all of the data blocks :/

I also need to be using O_DIRECT when repairing the database, and probably need to fix some other things about how commits work

**Comment by cberner** [comment]
I thought this over and decided that returning a `Result` is the right thing to do. Even though the current implementation uses `mmap` and looks like it can't fail, it's doing file IO and the implementation could change, especially given how platform dependent the performance and features of mmap is

**Comment by casey** [comment]
I think that's a reasonable position, but as a counter, I'd say that it's fine if it's made infallible now, even if you have to break the API and make it fallible in the future. It's nice to have a non-fallible API for a short or long period of time (maybe forever, if it never needs to be made fallible), and if you have to change it in the future, it's not a very painful change to adapt to.

**Comment by cberner** [comment]
Ya. However, after finding all the page cache issues, I've been thinking that maybe I'll switch away from `mmap` in which case it really should be fallible. If I'm going to implement a userspace cache to buffer writes anyway, it might not be much more work to cache reads too.
I added it to the list of APIs that I should revisit though

**Comment by casey** [comment]
Would switching away from mmap imply that reads wouldn't be zero-copy?

**Comment by cberner** [comment]
No, not necessarily. Reads could be served from the userspace cache and still be zero copy

**Comment by casey** [comment]
Ah, interesting. So it would actually have pretty similar performance characteristics, just instead of the OS managing the page cache and serving reads from that, redb itself would be managing a userspace cache. I wonder if it would be as fast, even if it was zero copy. It seems like the page cache is probably the best optimized, lowest overhead cache available. It's too bad it's just so fucked up.

**Comment by cberner** [comment]
So, the only fundamental advantage that I can see with the page cache is that the OS page cache integrates with the OOM killer, and so it can use an unbounded amount of memory because it can evict pages when there's memory pressure. Whereas a userspace cache will need to have a configured limit. On the other hand, that has the benefit of more predictable performance because it's not dependent on the memory usage of other processes on the system.

**Comment by cberner** [comment]
In fact, I just [updated the syscall benchmark](https://github.com/cberner/redb/pull/455) to compare mmap with writing into a `Vec` and it seems that mmap'ed memory (even anonymous memory that's not backed by a file) has ~40% overhead on writes. Dunno what the OS is doing there, but that suggests that a userspace cache could be faster
