### ISSUE TITLE
Can you add some "good-first-issue" tag?

### ISSUE THREAD

**Issue by Shubham8287** [cberner/redb#446]
I was looking for projects to contribute to learn rust, I see a lot of exciting work is going on here. I am looking to contribute, None of the existing issues looks beginner friendly. It would be great If you can create some.
Sorry for create one more issue :)

**Comment by cberner** [comment]
Sorry, but no I don't have time to do that right now. You may be able to find some good project to contribute to here though: https://goodfirstissue.dev/language/rust
