### ISSUE TITLE
File locks flaky on Windows?

### ISSUE THREAD

**Issue by casey** [cberner/redb#449]
I've been working on enabling Windows CI for `ord`, and I'm getting some strange `Database already open. Cannot acquire lock.` errors. The code is unmodified between unix and windows, so I'm wondering if the file locking/unlocking code on windows is working correctly. The errors are inconsistent, so the same test might pass or fail with no code changes on different runs.

**Comment by cberner** [comment]
I'm pretty sure this is a race in your tests. I added some debug logging, ran it on a Windows laptop, and it shows that you're opening "regtest\index.redb" a second time before the first one is closed. I can make a branch with the code, if you need

**Comment by casey** [comment]
Oh nice, good find! I'll look into it. Any idea why this would pass on Linux/MacOS but fail on Windows? Maybe there's a difference in semantics between the two platforms.

**Comment by casey** [comment]
> I can make a branch with the code, if you need

Yah, that'd be great.

**Comment by cberner** [comment]
Done. See the ord_windows branch

**Comment by cberner** [comment]
> Any idea why this would pass on Linux/MacOS but fail on Windows? Maybe there's a difference in semantics between the two platforms.

Not sure. It looks like your tests maybe spawn background processes though? If so, perhaps you need to do something extra to wait for them to finish on Windows

**Comment by casey** [comment]
Figured it out: We're using `dirs::data_dir()` to determine where to put the ord index. `dirs::data_dir()` consults `$HOME`, so during tests we set the `$HOME` variable to point to a tempdir. This doesn't work on Windows, so tests wind up using the same data directory.

Thanks for pushing that branch with debug statements!

**Comment by cberner** [comment]
Ah nice. Ya, for sure!
