### ISSUE TITLE
Question related to Redb data size

### ISSUE THREAD

**Issue by chungquantin** [cberner/redb#456]
I saw there is a benchmark table show the speed of Redb, it's quite fast. How about a volumn, is it small compared to other embedded key-value storages like RocksDB or LevelDB.

**Comment by cberner** [comment]
I haven't done any rigorous comparisons, but anecdotally I think it's a little more efficient than lmdb: I ran some tests a while back with both configured to the same maximum size limit and lmdb threw an out of space error and redb did not.
