### ISSUE TITLE
Detect when database is from old version of redb

### ISSUE THREAD

**Issue by casey** [cberner/redb#479]
We'd like to be able to print a nice error message if the user uses ord to open an index that was built with an incompatible version of redb. Would it be possible to add this case to the Error enum, so we can detect it and display a good error message? 

Something like this:

```
Error {
  VersionMismatch {
    database: u64,
    expected: u64,
  }
}
```

So we can detect both if our version of ord is newer than the index (user should delete index) and if our version of ord is older than the index (user should delete index or update ord).

**Comment by cberner** [comment]
Ya, I can have it return an error instead of panicking. Would `Error::Corrupted` work? I don't think including the version number is necessarily a good idea because you can't expect those to be monotonic (when redb reaches 1.0, I plan to change the version number to 1)

**Comment by casey** [comment]
`Error::Corrupted` is okay, but it would be nice to distinguish a version mismatch from corruption, since corruption is a somewhat extraordinary event, and the user might want to know that they have disk corruption or they otherwise messed up the index.

You could use a version number that used a byte for major, a byte for minor, and a byte for patch, so 0xAABBCC, and 1 would be 0x010000, and earlier versions would be 0x00XXXX.

**Comment by cberner** [comment]
Does #480 cover your use case? You'll get `UpgradeRequired` if the on-disk format is too old, and `Corrupted` if it's too new. I left it returning `Corrupted` if the format is too new, because that case is basically indistinguishable from a corrupted file.

**Comment by casey** [comment]
Yah, that's great!
