### ISSUE TITLE
Storing `TableDefinition`s in a struct's field

### ISSUE THREAD

**Issue by jeromegn** [cberner/redb#488]
I have a schema that looks like `uuid -> u64 -> &[u8]` so I'm using multiple tables with names like `"actor|<uuid>"` that have a definition like: `TableDefinition<u64, &[u8]>`.

These are dynamically created as needed, I keep a cache so I don't have to allocate strings so much and create a `TableDefinition` every time.

Something like:

```rust
struct MyStruct {
  cache: HashMap<Uuid, TableDefinition<'static, u64, &[u8]>>,
}
```

The problem is that table definition forces me to specify a lifetime for the `&[u8]`.

Any tips on making this work? The lifetime is not linked to the TableDefinition lifetime which makes this a bit awkward.

Would it be possible to implement `RedbValue` for `Vec<u8>`, allowing to read from it by ref as if it was a slice?

Related question: What are the implications of using a lot of "smaller" tables vs fewer bigger tables? I could redefine my schema to use a single table and serialize the key from the uuid + u64.

**Comment by cberner** [comment]
I'm pretty sure you can just specify `&'static [u8]`. Those lifetimes are annoying, but they don't effect the `get()` / `insert()` APIs.

**Comment by cberner** [comment]
The number of tables impacts the `open_table()` API. Performance scales logrithmically with the number of tables, so it shouldn't matter much unless you create millions of tables

**Comment by jeromegn** [comment]
Thank you!

What's the impact of a huge table? I can serialize my keys as `&[u8]` by making a buf of `u128 + u64` and store all of that there.

I'd be truncating the data after a certain threshold for each uuid, so in theory it should never store much more than 10K entries per uuid. We may eventually get to tens of thousands of uuids though, so the worse case would be a ~1B entries in a single table.

More concretely: Is it better to have 100K tables with 10K entries each or a single table with 1B entries?

In the many tables scenario:
- I need to list these tables on startup
- I'd have to `open_table` quite frequently

In the single big table scenario:
- I'd have to do ranges very often (I am assuming this is not a huge issue given it's a BTree structure)

This is likely a very difficult question to answer without saying "it depends" 😄. I'm only trying to understand the tradeoffs between the 2 approaches.

**Comment by cberner** [comment]
I've only tested cases with small numbers of tables, so I'd do the single table. Everything is b-trees so number of tables will impact the `open_table` time, and size of the table will impact the time to do operations on the table. If you really care about performance, you should benchmark both. Otherwise, I would do whatever is most natural for your application
