### ISSUE TITLE
Implement drain_filter

### ISSUE THREAD

**Issue by jeromegn** [cberner/redb#493]
Is it possible to iterate (either via `.iter()` or `.range(..)`) a table within a write transaction while also being able to delete data?

It's not possible right now (as far I can tell) because of mut borrow rules.

For example, in this code, table cannot be borrowed as mut because it is also borrowed immutably.:

```rust
let db = redb::Database::create(&db_path)?;

let mut tx = db.begin_write()?;

{
    let mut table = tx.open_table(TableDefinition::<u8, u8>::new("my_table"))?;

    table.insert(0, 0)?;

    for (k, v) in table.iter()? {
        table.remove(k.value())?;
    }
}

tx.commit()?;
```

`persy` exposes something like that for its iterators: https://docs.rs/persy/latest/persy/struct.TxIndexIter.html#method.next_tx

Perhaps a `iter_mut` and `range_mut` could create different types that keep a `&'a mut Table`, which can then be retrieved during iteration with `next_table`. Probably not a great name, but just an idea.

**Comment by cberner** [comment]
Not at the moment. In the future I'll probably implement `drain_filter`, which I think would do what you want. There's already `drain` if you only need to remove a specific range

**Comment by jeromegn** [comment]
Ah yeah, that would work!

> There's already `drain` if you only need to remove a specific range

Somehow I missed that. Even look now, I can't find that function anywhere. A bit puzzling. https://docs.rs/redb/latest/redb/struct.Table.html?search=drain

I can see it in the code, but it doesn't appear in the docs.

**Comment by cberner** [comment]
Ah, I forgot to document it. Should be fixed by https://github.com/cberner/redb/pull/494
