### ISSUE TITLE
WASI support?

### ISSUE THREAD

**Issue by GregoryConrad** [cberner/redb#507]
Hi! I was looking to see if redb could compile to `wasm32-wasi` and came across a handful of issues (with mmap and file locking):
```
unresolved import `crate::tree_store::page_store::file_lock::LockedFile`
failed to resolve: use of undeclared type `MmapInner`
cannot find type `MmapInner` in this scope
```

I was wondering if you would be willing to support WASI as a compilation target in redb. I might be able to PR to fix the above compilation issues and test the following functionality:
1. mmap (which it looks like you may have grabbed from the unmaintained `memmap` crate?) can probably be fixed by just copying the unix implementation (WASI has a libc that should be the same as unix)
2. file locking may be exposable from unix like mmap; but I am not sure. Some file locking APIs are not available in WASI libc

**Comment by cberner** [comment]
If it can be added as cleanly as the Windows support, then ya I'm open to merging a PR for wasm support

**Comment by GregoryConrad** [comment]
Great! I'll do some experimenting later to see how plausible it is with the current file locking mechanism.

On a completely different note, does redb support "unlimited" key/value sizes, or is there some hard limit? I didn't see any mention in the README or design.md. I.e., what happens if a key exceeds the page size?

**Comment by GregoryConrad** [comment]
Alright, some initial findings:

It looks like WASI support will actually be possible sometime in near-ish™️ future, at least using nightly! The errors I'm encountering during compilation come mostly from `libc`, which are fixable on `libc`'s end. This is because the default `libc` does not include bindings for `mmap` and file locking. `mmap` is already in wasi-libc, and file locking should be coming soon due to the recent spec update here: https://github.com/WebAssembly/wasi-filesystem/issues/2

The only changes necessary should be adding a cargo feature to `libc` with mmap support and then waiting for file locking support to trickle down through wasi-libc.

**Comment by GregoryConrad** [comment]
See https://github.com/rust-lang/libc/issues/3091

**Comment by GregoryConrad** [comment]
From my comment in #508:

> Based on https://github.com/WebAssembly/wasi-libc/blob/main/libc-bottom-half/mman/mman.c, it looks as though redb compiled to WASI would only work in read-only, if at all. Closing this PR as I don't think it makes any sense at the moment.

**Comment by brianorwhatever** [comment]
wasm support even if read only would be amazing

**Comment by GregoryConrad** [comment]
Since the `mmap` backend is gone now, this issue can be revisited since that was the blocking issue before. I've done a little experimenting and this is looking somewhat promising, at least when using nightly.

**Comment by GregoryConrad** [comment]
For future implementation:
- Once `wasi-libc` gets flock and those changes propagate to Rust's `libc`: https://github.com/GregoryConrad/redb/commit/97b46ff54d599d250980aa5ea7efc8146787b90f [0001-Example-commit-for-when-WASI-has-flock.patch](https://github.com/cberner/redb/files/11583228/0001-Example-commit-for-when-WASI-has-flock.patch)
- Once wasi no longer requires nightly:
https://github.com/GregoryConrad/redb/commit/896011d6f82d5cafddd182b74695cc7a341c55ee [0001-Example-commit-for-when-WASI-no-longer-requires-nigh.patch](https://github.com/cberner/redb/files/11583229/0001-Example-commit-for-when-WASI-no-longer-requires-nigh.patch)

**Comment by dpc** [comment]
What would it take to support indexeddb as a backend for `wasm32-unknown-unknown`? Am I wrong thinking that indexeddb could serve as a block allocator for redb?

**Comment by GregoryConrad** [comment]
Pretty sure all you’d need to do is implement this trait for indexeddb: https://docs.rs/redb/latest/redb/trait.StorageBackend.html

**Comment by teohhanhui** [comment]
> indexeddb

Unfortunately that's really not a good idea:

https://rxdb.info/slow-indexeddb.html (https://news.ycombinator.com/item?id=29314766)

It seems like what we really want for modern browsers would be https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system

**Comment by dpc** [comment]
Even snail slow redb in wasm would be useful sometimes.
