### ISSUE TITLE
Potential performance issue on btrfs

### ISSUE THREAD

**Issue by cryptoquick** [cberner/redb#509]
Hi, I'm on an older, dual core laptop running Garuda Linux. It comes by default with btrfs and zstd compression enabled. I'm running casey/ord, and I found a number of btrfs processes taking up about as much as ord during the indexing process. See:

![Screenshot from 2023-01-27 15-53-23](https://user-images.githubusercontent.com/285690/215221794-869feb4b-913a-4767-9181-afd4225964d9.png)

Sometimes these brtfs workers spike to 15% CPU utilization over four threads. That's pretty significant.

**Comment by cberner** [comment]
That seems expected. ord creates a large db file, so it won't fit in memory, and with zstd compression your CPU has to compress/decompress for all the redb accesses.

Are you aware of an optimize that redb should be making to avoid that?

**Comment by cryptoquick** [comment]
I don't know of one. If this is to be expected, then I'll just close this issue. Thank you for taking a look.

**Comment by cryptoquick** [comment]
Heads-up, @cberner, I started running into serious hardware issues after running an index. It didn't get all the way through before my OS had set my filesystem to read-only mode. It took a couple reboots to recover. I think there's some sectors on my SSD that got trashed, I'm gonna run through [these instructions](https://unix.stackexchange.com/questions/598970/check-read-only-btrfs-volume) after my rsync -a backup finishes.

I would recommend adding a panic if this is ever run on btrfs or any other CoW filesystem, since this could result in serious damage. It ran perfectly fine on an ext4 drive.

**Comment by cberner** [comment]
Yikes! That sounds like a bug in btrfs. I'd recommend reporting it upstream. redb only uses standard io: `write()` or writes into `mmap()` memory, so it seems unlikely that this is redb specific

**Comment by cryptoquick** [comment]
I think that's to be expected of CoW file systems. If the data structure serializes into different bytes in different places each time it's written, that would be a very bad thing for Copy on Write filesystems. It'd be better if it used append, or maybe a deterministically serialized byte order for the datastructures that are encoded on-disk.

**Comment by cberner** [comment]
Yes, this write pattern my not be optimal for a CoW filesystem, but that should only result in poor performance. Triggering it to go read only sounds like a bug

**Comment by cryptoquick** [comment]
It wasn't immediate, only after many tens of gigabytes of data being constantly rewritten hundreds of thousands of times did I start to experience hardware-level issues, not really a fault of the fs itself per se. This was on a separate, much more powerful computer than the one screenshotted above, with a 4TB NVMe 4.0 drive less than six months old.

**Comment by cberner** [comment]
I see. I'm trying to reproduce this on a spare 512GB NVMe that I have, which I've formatted as btrfs. Overall though, this sounds like a btrfs bug or bad hardware

**Comment by cryptoquick** [comment]
It's hard to know exactly what part of the stack it is, I'd be curious if you weren't able to repro, maybe try booting into this flavor of Linux: https://garudalinux.org

You won't need to install it, it works fine from USB for testing purposes. Maybe it has something to do with the way Garuda handles btrfs, not btrfs itself? This will be helpful so I can approach the appropriate community.

**Comment by cberner** [comment]
I'm up to block 400k with ord and still no issues. However, I did find an fix a bug (https://github.com/cberner/redb/pull/516) that could, at least in theory, cause undefined behavior. How long did you have to run ord for before you ran into this, and can you retry it with redb version 0.13?

**Comment by cberner** [comment]
Here are some additional details of my setup in case you want to debug further:
Kernel: 5.15.0-58-generic
OS: Ubuntu 22.04
NVMe: Samsung 950 Pro 512GB

Going to close this, as I think it's either fixed or not an issue with redb. Feel free to re-open though if you find new evidence that this is a redb bug
