### ISSUE TITLE
Subscribe to changes on key prefixes

### ISSUE THREAD

**Issue by vincent-herlemont** [cberner/redb#512]
Is the possibility of adding an observer like sled (example: [sled/watch_prefix](https://docs.rs/sled/latest/sled/struct.Tree.html#method.watch_prefix)) is planned?

**Comment by cberner** [comment]
Probably not, since it would be an awkward fit with the transaction model. But what is your use case?

**Comment by vincent-herlemont** [comment]
The use case is to stream data that has been guaranteed to be saved on disk. Useful for applications made with event streams.

Databases with transaction offer this functionality; example with PostgreSQL [`NOTIFY`](https://www.postgresql.org/docs/current/sql-notify.html). So, why is it an awkward fit with the transaction model?

**Comment by cberner** [comment]
Oh ya, I think you can already do that. Just use a separate channel like a `CondVar` or an `mpsc` to notify after calling `commit()`, then start a read transaction

**Comment by vincent-herlemont** [comment]
Ok, thanks for your answers 🙂. I close this issue.
