### ISSUE TITLE
Support `scan_prefix` for `ReadonlyTable<&str, T>`?

### ISSUE THREAD

**Issue by Eliot00** [cberner/redb#530]

**Comment by cberner** [comment]
What would this function do?

**Comment by Eliot00** [comment]
> What would this function do?

sled has a doc https://docs.rs/sled/latest/sled/struct.Tree.html#method.scan_prefix

**Comment by cberner** [comment]
Have you tried `range()`? I think you can accomplish this with `range(prefix..concat(prefix, '\0'))`

**Comment by Eliot00** [comment]
Maybe I just need a trie
