### ISSUE TITLE
Benchmark with Persy

### ISSUE THREAD

**Issue by satvikpendem** [cberner/redb#531]
I'm interested in seeing benchmarks with other KV stores like Persy.

**Comment by cberner** [comment]
Feel free to fork the benchmarks and implement it! I'd be interested to see it also, but am not interested in maintaining those benchmarks.

**Comment by marvin-j97** [comment]
> I'm interested in seeing benchmarks with other KV stores like Persy.

I have an extensive Rust KV benchmark repo: https://github.com/marvin-j97/rust-storage-bench @satvikpendem
