### ISSUE TITLE
Batch writes performance

### ISSUE THREAD

**Issue by RCasatta** [cberner/redb#532]
I have a crate using `rocksdb` but I dislike its compile times and wanted to migrate to `redb`.

Unfortunately batch writes timing in my quick test is much worse https://github.com/RCasatta/blocks_iterator/pull/67 than the redb benchmark shows. About 6 times slower with None durability (and huuuuuge db file), 30 times slower with Eventual or Immediate durability.

Am I doing something wrong? Are there possible improvements?

**Comment by cberner** [comment]
What kind of drive did you benchmark? SSD, HDD, NVMe?

**Comment by RCasatta** [comment]
Nvme

**Comment by cberner** [comment]
What is the difference between run 1 & run 2? Am I reading the results correctly that redb is only slow the first time?

**Comment by cberner** [comment]
I didn't read through your PR in a lot of detail, but am I right that your rocksdb implementation [doesn't flush the data after writing it](https://github.com/RCasatta/blocks_iterator/pull/67/files#diff-d85d00e428fcb026ae38d5a94e5bd918cc995c815a20b2ffd0151bce0d4e3788L137-R153)? If so, then `Durability::None` would be the most appropriate comparison.

**Comment by RCasatta** [comment]
> What is the difference between run 1 & run 2? Am I reading the results correctly that redb is only slow the first time?

Yes, only the first time becaus in the first time there are batch writes, the second time only reads.

> If so, then `Durability::None` would be the most appropriate comparison.

`Durability::None` That would fit my use case fits my use-case. But the issue I can't explain is that the db file space differs very much: 

* `Durability::None` 8.59GB
* `Durabilty::Immediate` 135 MB
* `Durability::Eventual` 101 MB

**Comment by cberner** [comment]
Ah right, `Durability::None` disables the GC. I'd suggest doing a `Durability::Immediate` commit every so often to keep the file size down.

**Comment by dpc** [comment]
Hi. I'm another dev looking to avoid using rocksdb for the same reasons. Thank you for redb, looks really neat.

It seems sensible to add some functionality that would flush periodically (either each N times, or when more data accumulated than certain threshold). In a complicated codebase tracking when to flush might be complicated and basically wrapping `Database` into some newtype adding tracking & flushing. Some `Durability:Threshold` with configurable (on `Database` threshold) would first: raise this issue to the developer  (right now seems very easy to overlook), seem quite natural. As a redb user I can probably say "I don't want to risk losing more than 50MB of last writes" etc.
