### ISSUE TITLE
Support go language?

### ISSUE THREAD

**Issue by echoWeb3** [cberner/redb#533]
There is a project written in rust. It uses this package to store the .redb database. Is there any way I can read this file in go language? Or can I use the go language to call the redb package of rust?

**Comment by cberner** [comment]
Nope. Or at least I have not built anything to do that. You would need to build some FFI bindings in Go

**Comment by echoWeb3** [comment]
Thank you for your reply, do you have any plans for this? I am a rust novice, and I can't spend a lot of energy learning it.

**Comment by cberner** [comment]
No, I don't. I may add Python support one day but do not plan to add any other languages

**Comment by Ralith** [comment]
C bindings for redb would be a useful foundation for access from many other languages. Might be much easier to just ask the maintainers of the downstream tool to support exporting to JSON or similar, though.
