### ISSUE TITLE
panicked at 'Tried to repair an empty database'

### ISSUE THREAD

**Issue by ricochet1k** [cberner/redb#547]
```
thread 'main' panicked at 'Tried to repair an empty database', /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.14.0/src/db.rs:200:14
```

This happens after simply creating a database. Put this in main and run the program twice in a row.
```rust
let db = Database::create("foo.redb")?;
```

Simply opening a table is enough to work around for now.

**Comment by cberner** [comment]
Oddly I'm not able to reproduce this. What OS are you using?

**Comment by ricochet1k** [comment]
MacOS M1. It's possible the trigger is to create the database and then
kill/ctrl-c the process.

**Comment by ricochet1k** [comment]
Yeah, killing the process is definitely the trigger after some more
testing. Still though if you create a table and commit the transaction
before killing the process it doesn't complain about repairing the next
time.
--
Matt Peterson

**Comment by cberner** [comment]
Ah I see. Well good news, this is not a bug. Bad news, this is a feature that I have intentionally left in at the moment: I figured repairing an empty db would be rare, and so added this assert to avoid any data loss bugs where the db is mistakenly detected as empty
