### ISSUE TITLE
Android Probability Crash

### ISSUE THREAD

**Issue by morn-0** [cberner/redb#556]
![image](https://user-images.githubusercontent.com/90960002/232315168-8d16edb1-0f5a-4386-b469-f47a039abf23.png)
This is the crash call stack.
It looks like the crash point is at https://github.com/cberner/redb/blob/master/src/tree_store/btree.rs#L52

redb is used by me to cache messages on websocket, inserting them when they come in and removing them when they are successfully consumed. crash happens on some phones, I'm not sure if it has something to do with different versions of db format.

**Comment by cberner** [comment]
Unfortunately that backtrace is just from a poisoned lock, presumably during panic unwinding, and not the actual error. Can you run with RUST_BACKTRACE=full? Or even better, do you have a way to reproduce this?

**Comment by morn-0** [comment]
> 

I can't reproduce it at the moment, I'll try to reproduce the problem in the next two days

**Comment by cberner** [comment]
I found a bug that could potentially cause this, although it's impossible to know without a repro. Feel free to re-open if you continue to have this issue after that PR lands.
