### ISSUE TITLE
Self-Referential Types in Redb Wrapper

### ISSUE THREAD

**Issue by vincent-herlemont** [cberner/redb#558]
I am facing an issue while trying to create a wrapper for the redb library to automate some table creation and insertion tasks. I am attempting to use `WriteTransaction` and `Table` within the same structure, which leads to a self-referential type that causes problems.

Here's an example of the structure `UseTransaction` with `WriteTransaction` and Table as fields:
```rust
...
struct UseTransaction<'db, 'txn> {
    txn_write: WriteTransaction<'db>,
    cache_table: Option<Table<'db, 'txn>>,
}

impl<'db,'txn> UseTransaction<'db,'txn> {
    fn open_table(&'txn mut self) { // I need to specify 'txn here, otherwise I get the error "lifetime may not live long enough" for &mut self.
        let table = self.txn_write.open_table();
        self.cache_table = Some(table);
    }
}
...
```

The issue is that this generates an exclusive borrow of `UseTransaction<'db>` which makes it [unusable](https://users.rust-lang.org/t/lifetime-error-with-nested-struct-redb-writetransaction/92684/15?u=vincent-herlemont) afterward and conflicts with the [`Drop` method of `Table` ./src/table.rs#L177-L180](https://github.com/cberner/redb/blob/27f04bf1a6cd6d4c3ce4e9280f386e310ac6c9a5/src/table.rs#L177-L180).

Here's a simulation of what happens when using the redb types: [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3762d11aaddced435f96c4d713343176).

I request advice on resolving this issue or alternative approaches to achieve the goal.

---

Related topics: [Lifetime error with nested struct (redb::WriteTransaction)](https://users.rust-lang.org/t/lifetime-error-with-nested-struct-redb-writetransaction/92684)

**Comment by cberner** [comment]
`Table` borrows the `WriteTransaction` and Rust does not allow self referential structs, so I don't think that is possible. You will have to split it into two wrapper structs: one for Table and one for Transaction
