### ISSUE TITLE
`UpgradeRequired(111)` error when updating to v0.16.0

### ISSUE THREAD

**Issue by Guilospanck** [cberner/redb#567]
Hi! First of all, thanks for the work on this!

I started using it this last week and then I noticed that when I upgraded the version to the `v0.16.0`, the old (`v0.15.0`) `.redb` database is raising an `UpgradeRequired(111)` error when running `Database::create("something.redb")`. When I go back to `v0.15.0` works just fine.

I saw the error is because [of this](https://github.com/cberner/redb/compare/v0.15.0...v0.16.0#diff-3ac6fd12694a9b235bb960ed5a3558cf50327901899252cfaf9ed0d68de72933R38) and that when version 1.0 comes along, it will be changed to `1`.

The question is: is there any workaround to make the old database right now work with the new version, like changing manually the version of the DatabaseHeader to be, in this case, `112`?

**Comment by cberner** [comment]
No. I increment the file format version number when the file format changes in a way that is backwards incompatible. You will need to recreate the database, or dump the old one and reimport it

**Comment by Guilospanck** [comment]
Thanks for the info! Closing it 🫡
