### ISSUE TITLE
`ReadableTable::range` ergonomics issue

### ISSUE THREAD

**Issue by andyyu2004** [cberner/redb#580]
Hey, thanks for this awesome library!

I've run into an ergonomics issue with the `range` method on a table in which I want to store bytestring keys and values.

The following fails to compile with the error `the trait bound `[u8]: std::borrow::Borrow<&[u8]>` is not satisfied`. 

```
fn f(
    table: impl redb::ReadableTable<&'static [u8], &'static [u8]>,
    range: impl std::ops::RangeBounds<[u8]>,
) {
    table.range(range);
}
```

 I'm also unable to change the signature to be `impl RangeBounds<&'a [u8]>` as the method is part of a fixed trait.

I think the code above has a reasonable signature for `range` and ideally it should just work. I'd appreciate any pointers to getting this to compile. Also curious if `&'static [u8]` is actually the correct signature to use for this use case.

We would also need to add a `?Sized` bound to `KR: Borrow<K::SelfType<'a>> + 'a` to fix the other compile issue.

**Comment by cberner** [comment]
`[u8]` isn't going to work because your table has the `SelfType` = `&[u8]`, so you need to use `RangeBounds<&[u8]>` can you use `'_` instead of `'a`? What is the signature of the trait that you are trying to implement?

**Comment by andyyu2004** [comment]
It was an oversimplification for me to say that the interface was fixed. The crux of the issue is that I'm trying to define an interface general enough for `redb` as well as a lmdb wrapper `heed` (relevant method [here](https://docs.rs/heed/latest/heed/struct.Database.html#method.range)).

I can't think of a trait method signature general enough that will work for both. If I use a reference as you suggested it won't typecheck for `heed`. 

Is there a fundamental reason other than types not matching up for `RangeBounds<[u8]>` to not work for `redb`?

I've written up a condensed example below.

```
#![feature(anonymous_lifetime_in_impl_trait)] 

use std::ops::RangeBounds;

trait Scan {
    fn scan(&self, range: impl RangeBounds<&'_ [u8]>);
}

impl Scan for redb::ReadOnlyTable<'_, &'static [u8], &'static [u8]> {
    fn scan(&self, range: impl RangeBounds<&'_ [u8]>) {
        let _ = redb::ReadableTable::range(self, range);
    }
}

impl Scan for heed::UntypedDatabase {
    fn scan(&self, range: impl RangeBounds<&'_ [u8]>) {
        self.range(todo!(), &range).unwrap();
    }
}
```

**Comment by cberner** [comment]
Nope. It's just the type checking.

I see. I haven't worked with `heed`, but I use the `lmdb-rkv` wrapper in the benchmarks. I don't know if it'll be helpful, but the `common.rs` file contains a trait that I used to unify redb, lmdb, rocksdb, and a few other databases.

**Comment by andyyu2004** [comment]
Ok, I'll see if I can think of something that would generalize redb's `range` type signature enough to make this work. Are you still willing to accept breaking changes as it's pre v1? 

Thanks for the reference, I think the issue doesn't pop up there are there is only a `range_from` which doesn't try to be generic over `R: RangeBound`. The only solution for the original issue I can think of without changing `redb` is to have a different method for each type of range. i.e. `range_from`, `range_to`, `range_full` etc....

**Comment by cberner** [comment]
Yep! This is the perfect time to propose breaking changes. I have an RFC open, since I plan to stabilize the API fairly soon (#575 )

**Comment by andyyu2004** [comment]
I found a decent workaround thanks to this impl. `impl<'a, T: ?Sized + 'a> const RangeBounds<T> for (Bound<&'a T>, Bound<&'a T>)`.  You can then do `table.range((range.start_bound(), range.end_bound())`.
