### ISSUE TITLE
Open readonly table given a WriteTransaction

### ISSUE THREAD

**Issue by andyyu2004** [cberner/redb#601]
Is it possible to provide an api similar to the following on `WriteTransaction`?

This compiles but I'm not familiar enough with the internals to know whether it's correct.

```
impl<'db> WriteTransaction<'db> {
    pub fn open_readonly_table<'txn, K: RedbKey + 'static, V: RedbValue + 'static>(
        &'txn self,
        definition: TableDefinition<K, V>,
    ) -> Result<ReadOnlyTable<'txn, K, V>, TableError> {
        let header = self
            .table_tree
            .read()
            .unwrap()
            .get_table::<K, V>(definition.name(), TableType::Normal)?
            .ok_or_else(|| TableError::TableDoesNotExist(definition.name().to_string()))?;

        Ok(ReadOnlyTable::new(header.get_root(), PageHint::None, self.mem)?)
    }
}
```

**Comment by cberner** [comment]
It's possible, but why do you want that API? `Table`s should provide all the same functionality as a `ReadOnlyTable`

**Comment by andyyu2004** [comment]
I'm running into the restriction where it complains the `Table is already open`. I would prefer to not try to work around that and just call `open_readonly` if I only need a readonly view. 

Specifically, I have some code that wants to read that needs to work given either a read or write transaction. However, the write transaction still has to open a write table view just to do reads which prevents any further write views to be opened.  

Does that make sense? I can try write out an example if not.

**Comment by cberner** [comment]
Ya, I see, but unfortunately that's not going to work. The restriction about `Table already open` is to prevent aliasing: if there was a read-only table and a rw table at the same time, the read-only table could become corrupted when the rw table was modifed.
You either need to use the same rw table, or open a read-only table in a separate transaction

**Comment by andyyu2004** [comment]
Ah ok, that makes sense. Thanks for clarifying!
