### ISSUE TITLE
DB cache size question

### ISSUE THREAD

**Issue by raphjaph** [cberner/redb#628]
Is it correct that the cache size can only be set when the database is created? Is this an inherent unchangeably property of the database similar to the schema (table definitions etc.) or can it be changed later?

I'm thinking of this in the context of initially building an index. You would want to give the database a large cache and once it is built restart it with a smaller cache.

**Comment by cberner** [comment]
It's part of the `Database`, but not part of the file format, so you're free to change it for each call to `create()` / `open()`

**Comment by raphjaph** [comment]
Thank you, didn't realize I could use the builder to open an existing database.
