### ISSUE TITLE
Implementing Hot Backup of RedB Database to S3 Bucket While Write Operations Are In Progress 

### ISSUE THREAD

**Issue by vincent-herlemont** [cberner/redb#634]
I am currently working with RedB database and I'm facing a challenge with regards to regular data backups. I wish to make regular backups of my database to an S3 bucket, but I am unsure if it is possible to do so while write operations are being performed.

My primary concern is the potential for data inconsistency during the backup process if write operations are ongoing. I am interested in performing a 'hot backup', i.e., a backup operation that occurs while the database is actively in use and transactions are happening.

**Comment by cberner** [comment]
Yes, it's possible to do that from inside your process. You would call `Database::begin_read()` then read and backup the data you desire. It's not safe to copy the file itself while writes are in progress

**Comment by vincent-herlemont** [comment]
Thanks for the answer
