### ISSUE TITLE
Panic in verify_checksum_helper

### ISSUE THREAD

**Issue by metaworm** [cberner/redb#642]
```
thread 'main' panicked at 'internal error: entered unreachable code', ~/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/redb-1.0.4/src/tree_store/btree.rs:522:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0ab38e95bb1cbf0bd038d359bdecbfa501f003a7/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/0ab38e95bb1cbf0bd038d359bdecbfa501f003a7/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/0ab38e95bb1cbf0bd038d359bdecbfa501f003a7/library/core/src/panicking.rs:117:5
   3: redb::tree_store::btree::RawBtree::verify_checksum_helper
   4: redb::tree_store::table_tree::TableTree::verify_checksums
   5: redb::db::Database::verify_primary_checksums
   6: redb::db::Database::do_repair
   7: redb::db::Database::new
   8: redb::db::Builder::create
```

[redb-test.zip](https://github.com/cberner/redb/files/12010671/redb-test.zip)

**Comment by metaworm** [comment]
The test project is in https://github.com/metaworm/db-crash-test , run `RUST_BACKTRACE=1 cargo test -r` to trigger the possible panic

**Comment by nick07002** [comment]
same err.

**Comment by cberner** [comment]
I tried the db-crash-test you provided, but I wasn't able to reproduce the error. Can you tell me more about the system you are running it on? What OS, what type of disk...etc

**Comment by nick07002** [comment]
after deleting the redb file, indexing started and then failed like below, tried a couple times, same error.


after deleting, it started indexing and keep failing again:

[indexing blocks] ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░ 767427/798578[2023-07-13T23:28:39Z ERROR ord::index::updater] Couldn't receive txs expected value at line 1 column 1
[indexing blocks] ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░ 767429/798578[2023-07-13T23:29:11Z ERROR ord::index::updater] Couldn't receive txs expected value at line 1 column 1

**Comment by metaworm** [comment]
@cberner  I am using PopOS, a Linux system based on Ubuntu. For the sake of disk lifespan, I conducted the testing on a virtualized in-memory disk, specifically the tmpfs file system.

**Comment by cberner** [comment]
@metaworm odd, I'm using Ubuntu 22.04 and tried both with /dev/shm (tmpfs) and my main partition which is ext4. Neither reproduced the error you saw. Are you able to minimize the reproduction case any further?

**Comment by metaworm** [comment]
@cberner This is the minimal reproduction case. I encountered a situation during the actual usage of redb where redb was unable to recover after a process crash. That's why I wrote this brute-force test. Of course, the probability of triggering it is very low, so you may need to run it multiple times to reproduce it.

**Comment by cberner** [comment]
How long did you need to run it for to get it to reproduce?

**Comment by cberner** [comment]
@metaworm can you test with master? I believe I've fixed this: ran your repro for an hour and it passed.

**Comment by metaworm** [comment]
@cberner I have tried the latest redb version, and even after running my stress tests multiple times, I did not encounter the issue anymore. Thank you very much for your assistance.

**Comment by cberner** [comment]
Great!
