### ISSUE TITLE
Database Flush & Speed

### ISSUE THREAD

**Issue by jguhlin** [cberner/redb#643]
Hey, wondering if there is any way to speed up the insertion of ~116million k/v pairs?

Also it'd be nice to have a flush option to know that all pending Durability::Eventual writes have completed.

Cheers,
--Joseph

**Comment by cberner** [comment]
The main things that will speed it up are:
- call commit() infrequently
- increase the set_cache_size(), if you have enough RAM
- inserting in sorted order may help

Yes, if you perform a commit() with Immediate durability all Eventual durability commits will be flushed

**Comment by jguhlin** [comment]
Cheers, much appreciated.
