### ISSUE TITLE
Linking error on aarch64-apple-ios-sim

### ISSUE THREAD

**Issue by NiklasEi** [cberner/redb#645]
I am getting linking errors from `redb` trying to build a project on an M1 for the iOS simulator:

```
  = note: ld: building for iOS Simulator, but linking in .tbd built for macOS/Mac Catalyst, file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libiconv.tbd' for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `redb` (lib) due to previous error
```

**Comment by cberner** [comment]
I don't have access to a Mac or iPhone to test redb, but if you submit a PR to integrate it into the Github CI, I can take a look

**Comment by NiklasEi** [comment]
Thank you for closing this. While trying to reproduce the issue, I found out that my setup was causing it.

On the off chance that someone else ends up here while trying to make a mobile app using Bevy: try commenting out https://github.com/bevyengine/bevy/blob/8ba9571eedada4f3ff43cdf1402670b7fe7c280d/examples/mobile/build_rust_deps.sh#L21
