### ISSUE TITLE
Send trait for WriteTransaction and ReadTransaction

### ISSUE THREAD

**Issue by maxwellflitton** [cberner/redb#646]
I've been trying to send the transactions `WriteTransaction` and `ReadTransaction` over threads in async code. However, I can't get the code to compile due to the `Send` trait is not auto-implemented. Is it safe to merely implement the `Send` trait using the `unsafe` tag like how `Rocksdb` do for their transactions as seen below:

https://docs.rs/rocksdb/latest/src/rocksdb/transactions/transaction.rs.html#36

**Comment by tengkuizdihar** [comment]
What's your usecase on sending transaction between threads? If I may assume, are you trying to offload the redb stuff to another thread using `spawn_blocking`?

**Comment by cberner** [comment]
No. `WriteTransaction` contains a `MutexGuard` which is not `Send`. `ReadTransaction` should be `Send` though. Can you provide an example of the code and error you're getting with it?

**Comment by cberner** [comment]
See this test about `ReadTransaction` for example: https://github.com/cberner/redb/pull/650

**Comment by maxwellflitton** [comment]
@cberner hey sorry for the delay. I work for SurrealDB and was looking into using redb instead of rocksdb for the key value store but there's a lot of async for our transaction layers so would need the write and read to both have the Send trait as the tracking of the transactions is sent over multiple threads. I've revisited redb code and it looks like the `WriteTransaction ` now has the `Send` trait implemented? If this is the case I can look into implementing `redb` into surrealdb as a rust implementation would be a lot easier for WASM deployments due to Rocksdb being written in C.

**Comment by cberner** [comment]
Yes, I implemented Send. Give it a try
