### ISSUE TITLE
Question: Async Iterators

### ISSUE THREAD

**Issue by nv0skar** [cberner/redb#647]
Hey, I'm trying to find a key by value, I know I can do it with `redb::Range`'s `find()` or `filter()`. But, as I have to continuously serialize the retrieved value in order to compare it with the predicate, I want to resolve the predicate in a future (I'm using `Tokio` multi-threaded runtime). However, I can't figure out how to get it to work without the compiler yelling me about lifetimes. Any ideas? Thanks!

**Comment by nv0skar** [comment]
Hi,
I've finally managed to get around it, however not the way I'd have liked. Here is the sample:
```rust
async fn search(
        db: Arc<Database>,
        predicate: Self::Value,
        unique: bool,
    ) -> Result<Either<Option<UserID>, SVec<UserID>>> {
        let txn = db.begin_read()?;
        let table = txn.open_table(Self::TABLE_DEFINITION)?;
        let mut search: task::JoinSet<Result<Option<[u8; 32]>>> = task::JoinSet::new();
        for num in 0..table.len()? as usize - 1 {
            let db = db.clone();
            let predicate = predicate.clone();
            search.spawn(async move {
                let txn = db.begin_read()?;
                let table = txn.open_table(Self::TABLE_DEFINITION)?;
                let (key, value) = table.iter()?.nth(num).context("Element should exist!")??;
                if Self::Value::decode(value.value()).await?.eq(&predicate) {
                    Ok(Some(key.value().clone()))
                } else {
                    Ok(None)
                }
            });
        }
        if unique {
            while let Some(result) = search.join_next().await {
                if let Some(key) = result?? {
                    search.abort_all();
                    return Ok(Left(Some(key)));
                }
            }
            Ok(Left(None))
        } else {
            let mut found = SVec::new();
            while let Some(result) = search.join_next().await {
                if let Some(key) = result?? {
                    found.push(key);
                }
            }
            Ok(Right(found))
        }
    }
```
A quick explanation: instead of creating a read transaction and opening the table once, iterating through each key-value and calling `tokio::spawn()` from each iteration (which I can't get it to work) , I iterated through the length of the table (n), created a new read transaction, opened the table and obtained `n`th element. The problem is I don't know if constantly creating new transactions and opening the table may hurt performance, which I guess it does. Another approach I tried is copying the key and value outside of the `tokio::spawn`'s scope, which I didn't succeed neither. Is it possible to clone a transaction or a table?

**Comment by cberner** [comment]
Can you structure your code like:
```
for entry in table.iter() {
  let (k, v) = entry?;
  let k = k.clone();
  let v = v.clone();
  search.spawn(async move { ... do stuff with k & v })
}
```

I think that will avoid the lifetime issues. It's not possible to close transaction or tables, and even if I make them Send + Sync I think you'll have the same lifetime issues because table.iter() borrows &self

**Comment by nv0skar** [comment]
Sorry I forgot to tell that I've already tried the same workaround you're suggesting but  doesn't work neither... 😨

**Comment by cberner** [comment]
Can you provide an example and the error?

**Comment by nv0skar** [comment]
For this piece:
```rust
        for entry in table.iter()? {
            let (id, value) = entry?;
            let predicate = predicate.clone();
            let id = id.value().clone(); // AccessGuard cannot be cloned!
            let value = value.value().clone();
            search.spawn(async move {
                if Self::Value::decode(value).await?.eq(&predicate) {
                    Ok(Some(Self::Key::into_key(id)?))
                } else {
                    Ok(None)
                }
            });
        }
```
I get:
```
error[E0597]: `table` does not live long enough
   --> storage/src/object.rs:124:22
    |
105 |         let table = txn.open_table(Self::TABLE_DEFINITION)?;
    |             ----- binding `table` declared here
...
124 |         for entry in table.iter()? {
    |                      ^^^^^^^^^^^^
    |                      |
    |                      borrowed value does not live long enough
    |                      argument requires that `table` is borrowed for `'static`
...
155 |     }
    |     - `table` dropped here while still borrowed

error[E0597]: `id` does not live long enough
   --> storage/src/object.rs:127:22
    |
125 |             let (id, value) = entry?;
    |                  -- binding `id` declared here
126 |             let predicate = predicate.clone();
127 |             let id = id.value().clone(); // AccessGuard cannot be cloned!
    |                      ^^^^^^^^^^
    |                      |
    |                      borrowed value does not live long enough
    |                      argument requires that `id` is borrowed for `'static`
...
136 |         }
    |         - `id` dropped here while still borrowed

error[E0597]: `value` does not live long enough
   --> storage/src/object.rs:128:25
    |
125 |             let (id, value) = entry?;
    |                      ----- binding `value` declared here
...
128 |             let value = value.value().clone();
    |                         ^^^^^^^^^^^^^
    |                         |
    |                         borrowed value does not live long enough
    |                         argument requires that `value` is borrowed for `'static`
...
136 |         }
    |         - `value` dropped here while still borrowed


```

**Comment by nv0skar** [comment]
> What is the type of `Self::TABLE_DEFINITION`?
`redb::TableDefinition`

**Comment by cberner** [comment]
Oh. Ya, that's not going to work for generic `TableDefinition`. `RedbValue::SelfType` has a lifetime associated with it. You're going to need some kind of bound that allows you to get an owned type, or restrict the key and value types to be ones that are `'static`.

**Comment by nv0skar** [comment]
Yeah, but key and value aren't  trait's generics, actually both are `&'static [u8]`, `Self::TABLE_DEFINITION` is the trait's constant where I define the table name, as I said the key and value don't change.

**Comment by cberner** [comment]
Oh, then try to_vec() instead of clone()

**Comment by nv0skar** [comment]
> Oh, then try to_vec() instead of clone()

Ha, that actually worked !! But, I'm concerned about the performance penalty of constantly allocating, as I'm using this code for searching users in my program, which implies that that code will run very frequently, nevertheless, is waaay better that the previous workaround, I might explore copying the buffer to a `stackalloc` buffer to get some performance, if you have some advice for getting more performance out of it I'd highly appreciate it ! Huuge thanks for your help bro !

**Comment by cberner** [comment]
If there's an equivalent of `thread::scope` that might resolve the lifetime issue. For example, see how I use it in the multi-threaded tests to concurrently access two separate tables: https://github.com/cberner/redb/blob/c54cebb49fc07ea27df4fb1a089616ee1574e6b4/tests/multithreading_tests.rs#L55-L60

**Comment by nv0skar** [comment]
I see... I've encountered this [crate](https://github.com/rmanoka/async-scoped) which seems to address that feature in Tokio, however, I can't replicate the Tokio's `JoinSet`'s functionality with that crate...

**Comment by nv0skar** [comment]
May it be dangerous if I manually extend the lifetime?
```rust
        for entry in table.iter()? {
            let (id, value) = entry?;
            let predicate = predicate.clone();

            let id = unsafe { std::slice::from_raw_parts(id.value().as_ptr(), id.value().len()) };
            let value =
                unsafe { std::slice::from_raw_parts(value.value().as_ptr(), value.value().len()) };

            search.spawn(async move {
                if Self::Value::decode(value).await?.eq(&predicate) {
                    Ok(Some(Self::Key::into_key(id)?))
                } else {
                    Ok(None)
                }
            });
        }
```
I assume that the slice is owned by `AccessGuard` which is freed at the end of the loop iteration, so the code above shouldn't work, however it does...

**Comment by cberner** [comment]
Extending lifetimes like that is pretty much always undefined behavior from what I understand of Rust. I'm going to close this, since no changes to redb are needed
