### ISSUE TITLE
Does the size of the database file increase as the committing frequency increases?

### ISSUE THREAD

**Issue by zhiying8710** [cberner/redb#654]
When I reduced the block batch size of ord's committing from 5000 to 500, the final generated database file was approximately 10 times larger than before.

**Comment by cberner** [comment]
No. In general there should not be a strong relationship between commit frequency and final file size

**Comment by zhiying8710** [comment]
@cberner 
thanks for reply, u are right.
the thing is:
I forked the official `ord` repository and added rollback feature code from `https://github.com/okx/ord` (`redb version: 0.13.0`) to my `ord` repository (`redb version: 1.0.2`). In the `index.rs`added a new function named `backup_at_init`, and called it in the `server.rs`, it will adds a savepoint when the`ord` server start. However, if I start the `ord` server from scratch, the database file size will be very very large. If I do not call `backup_at_init`, the database file size will be normal.

**Comment by cberner** [comment]
Oh, ya you should not retain a savepoint for an extended period of time. The database file will be append-only while a savepoint is alive, since it has to retain all the old data

**Comment by zhiying8710** [comment]
got it, thanks!
