### ISSUE TITLE
How to perform search

### ISSUE THREAD

**Issue by basicfunc** [cberner/redb#655]
Hey, there I'm new to file-based database, I recently used only SQLite. This project seems suitable for my project but I have only one question how to perform full-text search and regex search over redb database as SQLite provide various commands for same. I know there are search engine based for same purpose, but can you help me with it how to perform searching.

**Comment by cberner** [comment]
redb is not a good choice for that. It is effectively a persistent `BtreeMap`.

**Comment by basicfunc** [comment]
So is there anyway that I could retrieve the whole Table to a HashMap or BTreeMap? So that I can feed it to [indicium](https://github.com/leontoeides/indicium)

**Comment by cberner** [comment]
Yes. See the documentation. There are methods to iterate over a table,
after which you can copy it.
