### ISSUE TITLE
How can I scan all records in a table, or search keys with a prefix

### ISSUE THREAD

**Issue by songday** [cberner/redb#662]
Hi, Thanks for providing such a good library.

I had two questions:
1. How can I scan all records in a table.
2. Search keys with a prefix, like: table.get("abc*"); or table.get_by_prefix("abc")

Thanks

**Comment by cberner** [comment]
1) Use the `.iter()` method
2) You can `.range()` and iterate through it until you find the end of the prefix

**Comment by songday** [comment]
Thank you for taking your time to give me solutions.
