### ISSUE TITLE
Reduce MSRV to 1.66

### ISSUE THREAD

**Issue by devrandom** [cberner/redb#670]
The next Debian stable (trixie) includes Rust 1.66.  I believe that redb works fine with this MSRV.

Distribution provided Rust toolchains are better validated than those distributed via rustup, etc..  This is especially important for security sensitive applications.

See also #648

**Comment by devrandom** [comment]
I would be happy to create a PR.

**Comment by cberner** [comment]
Sure. Ya, please send a PR
