### ISSUE TITLE
Stats on read transaction

### ISSUE THREAD

**Issue by onbjerg** [cberner/redb#672]
Currently it is only possible to get stats on the database using a `WriteTransaction`, but most of the time metrics are collected in another loop/outside of the writes. This makes it infeasible to export the stats periodically over e.g. a Prometheus endpoint.

Adding a way to get database stats on a read transaction (even if slightly out of date, e.g. w/o current dirty pages) would be nice

**Comment by cberner** [comment]
Unfortunately, I don't think this is possible. The page allocator information is single copy and can only be accessed in a write transaction. It should be possible to add per-table stats that are readable from a read transaction though, like you mentioned in your other issue
