### ISSUE TITLE
Note drop behavior for `Drain` and `DrainFilter`

### ISSUE THREAD

**Issue by onbjerg** [cberner/redb#675]
If you want to clear an entire table you would currently use `Table::drain(..)`.

It is not documented that dropping the resulting iterator actually consumes the entire thing for you, so one might assume that you would have to do it yourself to clear the table like so:

```rs
while table.drain(..)?.next().is_some() {
  // noop
}
```

It would be nice to note in the docs that you can actually just drop the iterator

**Comment by cberner** [comment]
Ah ya, good idea. Want to send a PR?
