### ISSUE TITLE
Future API changes to consider

### ISSUE THREAD

**Issue by cberner** [cberner/redb#677]
- [x] replace `drain` and `drain_filter` with `extract_if` to match `BtreeMap`. Waiting on the std API to stabilize, so we can match it. https://github.com/rust-lang/rust/issues/70530
- [x] constant time API to get the length of a `MultimapValue`
- [x] optimize `Table::len()` by storing the number of entries in a counter. See https://github.com/cberner/redb/issues/710
- [x] Introduce a common trait for all tables, including untyped ones, that has the `stats()` and `len()` methods
- [x] Implement `len()` for untyped tables
- [x] Rename `RedbKey` to `Key` and `RedbValue` to `Value`
- [x] Remove lifetimes from as many public structs as possible

**Comment by Gawdl3y** [comment]
I'm eager to see a lot of the lifetimes being removed from public structs, as I believe the lifetimes are making downstream use of vincent-herlemont/native_db kludgier than it could be. See vincent-herlemont/native_db#69 and vincent-herlemont/native_db#71.

**Comment by Ralith** [comment]
The lifetime relationships of `ReadTransaction` and `ReadOnlyTable` forced me to expose two layers of guard objects in https://github.com/Ralith/hypermine/blob/master/save/src/lib.rs, which is a mildly annoying wart in an otherwise ergonomic encapsulation of redb.

**Comment by cberner** [comment]
@Ralith can you give `master` a try and see if the new `'static` lifetimes resolves your issue?

**Comment by Ralith** [comment]
That avoids the double-guard for reads, but it looks like the problem still exists for writes. Not sure how solvable that is without making things more dynamic, though.

**Comment by cberner** [comment]
I plan to remove those too. Just haven't gotten to it yet

**Comment by eserilev** [comment]
Recently I was trying to do something like 

```
 let iter = {
            let read_txn = self.db.begin_read().unwrap();
            let table = read_txn.open_table(table_definition).unwrap();
            table.range::<&[u8]>(from..).unwrap().map(|res| {
                let (k, v) = res.unwrap();
                Ok((
                    K::from_bytes(k.value()).unwrap(),
                    v.value().to_vec(),
                ))
            })
        }
```

because of lifetime issues I couldn't find a way to return `iter` without unsafe Rust. The `'static' lifetime changes currently on master are a huge game changer for us. Really excited for this to land!

**Comment by cberner** [comment]
`master` now has much friendlier lifetimes

**Comment by Evrey** [comment]
For future changes i’d like to also suggest this one:

- Replace all occurrences of `String` with `beef::Cow<'static, str>` or `core::borrow::Cow<'static, str>` where possible.

This would obviously be a breaking change, hence »future change«.

I’m suggesting this, because currently there are a bunch of completely useless `String` allocations being performed in my code base. I only use `const` table definitions with `&'static str` table names, so all the error paths can take the name from my table definition directly, resulting in e.g. `TableError::TableDoesNotExist(Cow<'static, str>)`. To make it worse, usually i throw these `String` names away immediately, because when i am handling errors, i know which table i just opened and don’t need a copy of the name.

**Comment by cberner** [comment]
Unfortunately, I don't think that would work. The call site can have a non `'static` lifetime: https://github.com/cberner/redb/blob/222a37f4600588261b0983eebcd074bb69d6e5a0/src/transactions.rs#L1212

**Comment by Evrey** [comment]
Well, yes. I’m suggesting to borrow the name when it’s `'static`, and only allocate it when it’s not. Alternatively, have `TableError`s bound to the table definition’s lifetime (which i’d say makes sense to do), storing borrowed `&'a str`s, and have an `impl<'a> Into<TableError<'static>> from TableError<'a>` that allocates all `Cow<'_, str>` names, erasing the original lifetime.

**Comment by cberner** [comment]
> I’m suggesting to borrow the name when it’s 'static, and only allocate it when it’s not.

Do you have an example of the code for that? I'm not sure how to make it conditional on whether the lifetime is 'static or not

**Comment by Evrey** [comment]
Oh right. I’ve been surfing on too much nightly Rust and forgot you can’t specialise over lifetimes.

**Comment by Ralith** [comment]
> I plan to remove [write transaction lifetimes] too. Just haven't gotten to it yet

It looks like a double-guard is still needed for write transactions: [`WriteTransaction::open_table`](https://docs.rs/redb/2.0.0/redb/struct.WriteTransaction.html#method.open_table) borrows from the transaction, which means that an encapsulating API cannot store both the transaction and the tables in the same object.

**Comment by cberner** [comment]
Yes, that's correct. If you need it to be lifetime-less, I would recommend opening the tables on-demand rather than retaining them.

**Comment by Ralith** [comment]
That would work, but I hesitated since the cost of `open_table` isn't clear. What's a good mental model here?

**Comment by cberner** [comment]
It's log N in the number of tables in the database, and for repeat opens of the same table should end up being about as expensive as a few HashMap lookups

**Comment by Evrey** [comment]
Those are good numbers to document in APIs.
