### ISSUE TITLE
What are `AccessGuard`s for?

### ISSUE THREAD

**Issue by dpc** [cberner/redb#680]
It seems I'm just always calling `.map(v| v.value)` on everything for no good reason, so I'm wondering.

**Comment by onbjerg** [comment]
Seems like the `AccessGuard`s are a convenience to e.g. free references to a given database page (allowing it to be freed), or remove a given entry once the guard is dropped. I'd imagine, for example, that the guard returned by `Table::remove` only removes the entry once the guard itself is dropped

**Comment by dpc** [comment]
Oh. So can I hold on to them outside of ... holding reference to table? Holding reference to the whole transaction?

**Comment by cberner** [comment]
It has the same lifetime as the table that it was retrieved from

**Comment by dpc** [comment]
OK. So isn't/couln't table/transaction preventing modifications to the underlying data already?

The only thing I can think of `AccessGuards` is for, is delaying / skipping reading/deserialization of the given data itself, in case the caller just doesn't use them.

**Comment by cberner** [comment]
No. It's for the borrow checker. AccessGuard has the lifetime for which the
data is valid

**Comment by cberner** [comment]
I don't think so, but if you have a way of making it work I'd love to change it!

Take a look at the implementation and you'll see that `page` is an enumeration which sometimes own the memory and sometimes holds a reference to it

**Comment by dpc** [comment]
I took a deeper look, and indeed `AccessGuard impl Drop` to do some mutations to internal stuff, which can't be stashed into the user-defined `SelfType<'a>`.

Then I thought ... maybe `AccessGuard` could at least `Deref<Target=&'a SelfType<'a>>`, but that also doesn't work because `SelfType<'a>` is produced as owned by `from_bytes` and there is no way to tie the lifetimes. Maybe HKT could be used? But I don't think `Deref` supports that. I'm not sure, I'm actually not that good with lifetimes.


So then thinking a bit about it occured to me that at very least it should be possible to have owned versions of some APIs that just clone the `SelfType<'a>` and let the `AccessGuard` drop, avoiding this weird double-nested-map.

Kind of like this:

```
    fn get_owned<'a>(
        &self,
        key: impl Borrow<K::SelfType<'a>>,
    ) -> Result<Option<<<V as RedbValue>::SelfType<'a> as ToOwned>::Owned>>
    where
        K: 'a,
        <V as RedbValue>::SelfType<'a>: ToOwned,
        <<V as RedbValue>::SelfType<'a> as ToOwned>::Owned: 'static,
    {
        match self.tree.get(key.borrow()) {
            Ok(o) => Ok(o.map(|v| v.value().to_owned())),
            Err(e) => Err(e),
        }
    }
```

Unfortunately I ran out of time yesterday trying to get it to work. Conceptually, it works in my head. "If you have a V that you can Clone/ToOwned, then just do it eagly and save user the trouble". But for some reason borrowck things that ` v.value().to_owned()` is still holding on to that `v`, and my lifetime/generics-fu is not strong enough.

Before I commit to it and e.g. look for help, I wanted to describe the idea and even check if it's desireable, or you have a better one. @cberner

**Comment by cberner** [comment]
yes, that sounds like it would work, but I don't want to add it. I like to keep the interface as simple as possible, so I don't want to have two different get methods. I think it should be possible to implement that as a wrapper on top of redb

**Comment by dpc** [comment]
That's true. I can always get it in some extention trait if I really want it.

That concludes the issue. Thanks.
