### ISSUE TITLE
1PC+C instead of 2PC

### ISSUE THREAD

**Issue by janis-ab** [cberner/redb#686]
Hello everyone,

I have read an article about increased performance when using [1PC+C instead of 2PC](https://www.redb.org/post/2022/07/26/faster-commits-with-1pcc-instead-of-2pc/
), but the article and docs leaves some questions unanswered.

In a way this scheme does not convince me of data reliability/consistency unless doing checksum recalculation at each file open call.

Article contains pseudocode:
```rust
file.write(&data);
file.write(checksum(&data));
file.promote_to_primary();
file.fsync();
```

For this function call execution order at the point when fsync is called (while it "guarantees" that all writes are flushed out to disk upon successful return) it does not guarantee the ordering of writes; but the writing process could be interrupted at any time and for whatever reason and thus leaving data file in bad state.

So let's say a scenario that happens on disk after fsync call actually is:
```rust
file.promote_to_primary(); // i assume this writes data into some file page as well
file.write(checksum(&data));
// Let's say the next step does succeed partially due to power loss or process being killed, segfaulted, USB storage
// drive unplugged or whatever reason. Let's assume next action does write out some data, but only partially (some
// complete pages, some incomplete and some pages even lost).
file.write(&data); 
```

We could say that such a file is in an "inconsistent" state.

**How can a reader/writer know that the file it just now has opened and is accessing is consistent unless it checks checksums for all pages that were added in latest "transaction"?**

I mean, even if header pages are correct, it still does not give any guarantee that all data pages exist and are correct, right?
Thus if reader accesses only part of data and "luckily" those were completed writes, it never knows that the file (last transaction) is actually unfinished/inconsistent (i.e. some data missing). So in the end an application that bases it's calculations on data read from such file gives "wrong" results.

So as my understanding goes, every time when a file is opened, it is necessary to test checksums for all "new" pages that were introduced in the latest write transaction, right? How is it actually done in redb?

Checksums have to be checked (no matter if a file is opened for reading or writing) and only then appropriate action can be taken, thus "1PC+C" is slower on opens and so in cases when process opens/closes file often it should perform worse than 2PC especially if the latest write transaction did write a lot of pages, right?

Yeah, sure, it might be that re-checking latest transaction data is not so slow as it might seem at first, since if there are many readers, then those disk pages most probably would be cached in RAM, but my question is more about fact checking and understanding of current implementation so to know in which cases it performs well and in which not so well.

**Is there something more tricky done behind the scenes that is not written about in blog post? Is my reasoning sound or i have not taken something into account?**

**Comment by cberner** [comment]
Yes, there's one trick. There is a separate flag, the [RECOVERY_REQUIRED flag](https://github.com/cberner/redb/blob/d8be9580591aa063469df6a7faf243d17a5a59a6/src/tree_store/page_store/header.rs#L56), which is set to true when the file is opened. And it is set to false when the database goes through a clean shutdown.

The checksums are only checked if the file is opened and found to have the RECOVERY_REQUIRED flag set to true (indicating an unclean shutdown)

**Comment by janis-ab** [comment]
Okay, writer when opens a file sets RECOVERY_REQUIRED flag. But doesn't it mean that there still are two fsync calls, one for newly written data and then second just to unset this flag at the end of successful transaction? And essentially it becomes 2PC.

**Comment by cberner** [comment]
No, RECOVERY_REQUIRED is only unset when the database shutdown: `drop` is called on `Database`

**Comment by janis-ab** [comment]
Okay. Then i am interested in understanding two scenarios.

**1. Writer opens DB writes something and closes it:**
```rust
file.open();
file.RECOVERY_REQUIRED.set();
// no need to fsync, because file is locked, single writer allowed, right?

file.write(&data);
file.write(checksum(&data));
file.promote_to_primary();
file.fsync();

// Closing file
file.RECOVERY_REQUIRED.unset();
file.fsync();
```

**2. Writer is a long-living process, opens DB and writes something occasionally:**
```rust
file.open();
file.RECOVERY_REQUIRED.set();

// write transaction 1
file.write(&data);
file.write(checksum(&data));
file.promote_to_primary();
file.fsync();

//
// N more write transactions, where N > 0
//

// Closing file
file.RECOVERY_REQUIRED.unset();
file.fsync();
```

Is this is how things are expected to happen in both scenarios?

**Comment by cberner** [comment]
There's an fsync after RECOVERY_REQUIRED.set(), but otherwise yes that's correct

**Comment by janis-ab** [comment]
These little subtle details actually clarifies a lot. I think i've got the gist of it. Hope it helps others interested in inner workings as well.

Thanks' for the info and prompt replies!

I guess, case can be closed/archived.
