### ISSUE TITLE
How to close a DB

### ISSUE THREAD

**Issue by akashgurava** [cberner/redb#690]
I am doing some memory usage testing. It looks like the memory allocated for a DB is not getting. I tried to manually drop the Database instance and Create DB in a different function and exit that function but it's still using the memory.

**Comment by cberner** [comment]
How did you determine that it's still using the memory?

**Comment by akashgurava** [comment]
My activity monitor:
<img width="1072" alt="Screenshot 2023-09-27 at 9 01 52 PM" src="https://github.com/cberner/redb/assets/13036662/50016437-b383-47cc-bef2-86b8e29e4e14">

Profile using cargo instruments:
<img width="1396" alt="image" src="https://github.com/cberner/redb/assets/13036662/60078ccd-4b97-4f45-a027-8e83e06054bf">

```rust

fn verify_redb() {
    let db = make_db();
    let data = Data::rand_many(1_000_000);

    let write_txn = db.begin_write().unwrap();
    {
        let mut table = write_txn.open_table(DATA_TABLE_DEF).unwrap();
        data.iter().enumerate().for_each(|(i, data)| {
            table
                .insert(&(i as u64), data.to_db_bytes().as_ref())
                .unwrap();
        });
    }
    write_txn.commit().unwrap();

    let read_txn = db.begin_read().unwrap();
    let table = read_txn.open_table(DATA_TABLE_DEF).unwrap();
    let read_data = table
        .iter()
        .unwrap()
        .map(|d| Data::from_db_bytes(d.unwrap().1.value()))
        .collect::<Vec<_>>();
    assert_eq!(data, read_data);
}

fn main() {
    verify_redb();

    sleep(Duration::from_secs(10));
}
```

**Comment by cberner** [comment]
That could be the page cache. Try running verify_redb() in a loop and see
if you get an OOM. That would prove that it's leaking memory.

**Comment by akashgurava** [comment]
Seems like its cleaning up. Just not reflecting properly from activity monitor.
