### ISSUE TITLE
Implement `RedbValue` for `Vec<u64>` (and, more generally, for `Vec<RedbValue>`)

### ISSUE THREAD

**Issue by LilithHafner** [cberner/redb#691]
In most cases, Multimap Tables are a good substitute for Vec values. However, it would still be nice if `[u64]` and, more generally, `[RedbValue]` were supported. (possibly a subset of #666)

**Comment by cberner** [comment]
Unfortunately that's not possible due to endianess. You could implement a custom type, but it wouldn't be zero copy

**Comment by LilithHafner** [comment]
Could you pick a platform independent endianess and load and store consistently? I don't see how this poses endianess problems that aren't also present for `u64`.

**Comment by cberner** [comment]
u64 is already stored platform independent. The problem is that &[u64]
needs to be zero copy, and so it can't be converted to the native layout.
Vec<u64> might work. That could be implemented in a way that copies when
deserializing the data

**Comment by LilithHafner** [comment]
Okay, that makes sense.
