### ISSUE TITLE
Implement option to initialize database on creation

### ISSUE THREAD

**Issue by LilithHafner** [cberner/redb#693]
I want to open a possibly-non-existent database and, if it exists, use it as is, but if it does not exist, create it and initialize it by inserting some values. I don't see any great way to do this with the redb API. maybe I'm missing something. I would consider implementing and adding to the public API something like this
```rs
fn open_with_init<F>(path: &PathBuf, f: F) -> Result<Database, redb::DatabaseError> where F: FnOnce(&Database) -> () {
    match Database::open(path) {
        Ok(db) => Ok(db),
        Err(err) => {
            let db = Database::create(path)?;
            f(&db);
            Ok(db)
        },
    }
}
```
However, I imagine this can be implemented more efficiently with access to redb internals.

**Comment by cberner** [comment]
Can't you do `Path::exists()`? and then call `open()` or `create()` as appropriate
