### ISSUE TITLE
Efficiently getting the number of elements in a MultimapValue

### ISSUE THREAD

**Issue by dignifiedquire** [cberner/redb#697]
I was wondering if I can assume `MultimapValue::count()` to be efficient/fast or if there is a way to more effectively get the number of elements stored, when I don't need to actually read them.

**Comment by cberner** [comment]
No. It's a linear scan. If you need fast access to that stat I would store
it separately

**Comment by dignifiedquire** [comment]
I see, so this value is not stored internally in a form that could be easily exposed?

**Comment by dignifiedquire** [comment]
thanks
