### ISSUE TITLE
`len` is slow

### ISSUE THREAD

**Issue by casey** [cberner/redb#710]
Ord got really slow recently, and it turned out to be due to adding a call to `GIGANTIC_TABLE.len()`, which looks innocent, but actually iterates over the entire table. If it isn't too hard, it might be a good idea to cache the length so it can be a constant-time operation.

**Comment by cberner** [comment]
Ya, that seems like a good optimization to have. Unfortunately it will require a file format change. I'll add it to my list of things to look into for 2.0

**Comment by cberner** [comment]
Merged into #677
