### ISSUE TITLE
ReadTransaction::open_table errors on new tables

### ISSUE THREAD

**Issue by Licenser** [cberner/redb#711]
When calling `open_table` on a table that hasn't been created yet the call errors. It would be nice to either have the call create the table, have an option to pass to the call that defines the behavior, or have a different call that would act as `open_or_create_table`

edit(1):
The behavior of this function is workaroundable but it is clumsy:
```rust
        let known_nodes = match read_txn.open_table(NODES) {
            Ok(table) => do_stuff(table),
            Err(TableError::TableDoesNotExist(t)) => {
                info!("Table {t} does not exist, assuming it is empty");
                HashMap::new()
            }
            Err(e) => {
                return Err(r_err(dbg!(e)).into());
            }
        };
```

edit(2):

~~an alternative seems to be to always use  a write transaction but that's also not optimal~~ (not really as it violates some locking constraints)

**Comment by cberner** [comment]
That's not possible because read transactions are read-only. Another workaround is to use a write transaction at the beginning of your program to create all the tables that will be used

**Comment by Licenser** [comment]
Then as an alternative would it be possible to treat a table that doesn't exist when opened as empty instead of creating a hard error? That won't violate the read only constraint and lead to effectively the same outcome from a API perspective.

Ultimately the use case doesn't care if the table is created, just that it doesn't hard error :)

**Comment by cberner** [comment]
I think the current API is better, and ya as you noted this would break the current API so would need to go into a 2.0 release.

What's your use case where this is a problem and another workaround doesn't work well?

**Comment by Licenser** [comment]
Heya,

I don't say it will break the API, but change it. The change might very well be a new function or allow for a builder pattern like (names just ideas):

```rust
let read_txn = db.begin_read().allow_empty_tables();
// or
let table = read_txn.open_table_relaxed(NODES) ;
```

I want to use redb as storage for a openraft implementation, and yes, there are workarounds but all of them feel clumsy as they seem to work around a limitation that is not technically necessary.

**Comment by cberner** [comment]
Thanks for the suggestions, but I decided not to implement this. I think the use case is fairly niche and easy to work around, so I don't want to add additional surface area to the API.
