### ISSUE TITLE
Potentially unnecessary `&mut self` on methods.

### ISSUE THREAD

**Issue by andyyu2004** [cberner/redb#717]
I noticed that the code compiles fine if mutating methods `[MultiMap]Table::{insert,remove}` etc are changed to only require `&self`. Is there a reason they're currently requiring `&mut self`?

**Comment by cberner** [comment]
Yes, it would result in race conditions if multiple threads modified the same table at the same time

**Comment by andyyu2004** [comment]
Yep, makes sense. Could it work if it required `&self` but marked `!Sync`? This would make it more ergonomic for single thread use.

**Comment by cberner** [comment]
No, that would break the iterators returned from methods like range()
