### ISSUE TITLE
Change RedbKey and RedbValue to Key and Value

### ISSUE THREAD

**Issue by casey** [cberner/redb#727]
I think it's slightly more idiomatic to not prefix types with the crate name. If these names conflict with local type names, they can be referred to as `redb::Key` and `redb::Value`, which is still short, since `redb` is only four letters.

API breakage can be avoided by doing a hidden re-export:

```
#[doc(hidden)]
type RedbKey = Key;

#[doc(hidden)]
type RedbValue = Value;
```

**Comment by cberner** [comment]
ya, that does seem better. Although I'll probably go with `KeyType` and `ValueType` that seems more descriptive to me.

I'm getting a compiler error from the aliasing though. Do you know how to export an alias of a type with GATs? It looks to me like it's not possible: only generic params are allowed. https://doc.rust-lang.org/reference/items/type-aliases.html

**Comment by cberner** [comment]
> Oh that's annoying. I don't know if there's a workaround for that.

Ya, I don't think it's possible from what I can tell. I'm going to merge this into #677
