### ISSUE TITLE
Implement `RedbKey` and `RedbValue` for tuples larger than length 12

### ISSUE THREAD

**Issue by casey** [cberner/redb#733]
I tried to add a new field to a database value, and ran into the 12 element limit on implementations of RedbValue for tuples.

**Comment by cberner** [comment]
That's pretty easy to add. Want to send a PR? You just need to copy this line and extend it with the appropriate number of elements: https://github.com/cberner/redb/blob/master/src/tuple_types.rs#L323-L336

**Comment by casey** [comment]
For sure. How many more impls should I add? I'd be inclined to just double the number of impls, i.e., up to 24.

**Comment by cberner** [comment]
Ya, that sounds good. I picked 12 somewhat arbitrarily since it was the same number that std picked for implementing Ord...etc on tuples

**Comment by casey** [comment]
I ran into an issue here, RedbValue requires `Debug`, but debug isn't implemented for tuples of size 13 and above 😭. Can this bound be removed or relaxed? It looks like it's only used in debug code.

**Comment by cberner** [comment]
Oh, that's unfortunate. Hmm, it's pretty nice for the implementation of `Debug for Table`. Do you really need size 13 tuples? A struct that implements RedbValue, or nested tuples, would workaround this

**Comment by casey** [comment]
Yah, losing Debug for Table probably wouldn't be worth it.

We're using a nested tuple to work around this, and there are a few fields in the entry that could logically be grouped together, so we can work around this without too much difficulty.
