### ISSUE TITLE
Read-only storage backend

### ISSUE THREAD

**Issue by cutsoy** [cberner/redb#737]
I'm using redb in an environment that's both heavy-read and heavy-write, but rarely at the same time. I'm aware that redb doesn't support read/write concurrency, but I would like to find out if it's possible to support read concurrency (multiple readers at the same time, without any active writers).

This currently fails when using [`FileBackend`][1] because it immediately [acquires an exclusive lock][2] (which is necessary for eliminating concurrent writes of course). Would it be safe to implement my own [`StorageBackend`][3] that acquires a shared (non-exclusive) lock and returns errors in `set_len`, `sync_data` and `write`, implementing only read operations?

[1]: https://docs.rs/redb/latest/redb/backends/struct.FileBackend.html
[2]: https://github.com/cberner/redb/blob/4679855401f85b5e6c2fd52f3f6a182ef3096e7d/src/tree_store/page_store/file_backend/unix.rs#L37
[3]: https://docs.rs/redb/latest/redb/trait.StorageBackend.html

**Comment by cberner** [comment]
There's already support for multiple current threads as readers. If you need multiple processes though, yes I think what you're suggesting will work in theory. You may need to special case some writes into the db header, and I certainly don't promise to support this long term 😅
