### ISSUE TITLE
Fast .iter().skip(n).take(m)

### ISSUE THREAD

**Issue by casey** [cberner/redb#738]
We have a few places in ord where we're doing `.iter().skip(n).take(m)`. If `n` is large, this can be very expensive. Can this be made faster? I'm guessing it might require storing and updating the number of entries in each interior node, so that you can quickly get to the beginning of the range of values you want, but that might be expensive.

**Comment by cberner** [comment]
Ya, I don't see a good way to optimize this. Counts could be added to the interior nodes, but that'd require a file format change and would mean that fewer keys fit in each of them.

Have you profiled it? Possibly implementing `nth` would speed it up a bit by skipping some deserialization or comparisons. It'd only be a constant factor speed up though.

**Comment by casey** [comment]
I haven't profiled it, but I think it'll be super slow if there's any iteration. Would `nth` only return one element?

**Comment by cberner** [comment]
Ya, only one element, but it would still have to iterate to find that one.
The only potential optimization would be avoiding yielding all the
intermediate values

**Comment by casey** [comment]
For what it's worth, Postgres has this, [and mentions that it's slow](https://www.postgresql.org/docs/9.2/queries-limit.html):

> The rows skipped by an OFFSET clause still have to be computed inside the server; therefore a large OFFSET might be inefficient.

So it's probably reasonable to just not do this, given that Postgres doesn't as well.

**Comment by cberner** [comment]
Ya, I don't know of any database that optimizes OFFSET. Is there a way to
rewrite your query?

**Comment by casey** [comment]
I think the answer is to just add an index which contains the elements that we want, with a key which are sequential integers, so we can query it by range, which is fast.
