### ISSUE TITLE
build target `armv5te-musleabi` error

### ISSUE THREAD

**Issue by gngpp** [cberner/redb#747]
<img width="1150" alt="image" src="https://github.com/cberner/redb/assets/51810656/3ef93ebf-45b3-4059-a25a-4675ff896c84">

from: https://github.com/gngpp/ninja/actions/runs/7670049308/job/20905334896#step:7:2370

**Comment by gngpp** [comment]
I made a patch to fix 32 bit platform support compiling AtomicU64 using https://github.com/taiki-e/portable-atomic, if you agree I will open a PR to fix it

repo-patch: https://github.com/gngpp/redb.git

**Comment by cberner** [comment]
Sorry, but I don't want to add any new dependencies to redb
