### ISSUE TITLE
Non-destructive savepoint restoration

### ISSUE THREAD

**Issue by Ralith** [cberner/redb#748]
The only API I could easily find to use a savepoint is [`WriteTransaction::restore_savepoint`](https://docs.rs/redb/latest/redb/struct.WriteTransaction.html#method.restore_savepoint), which "invalidates all [Savepoint](https://docs.rs/redb/latest/redb/struct.Savepoint.html)s created after savepoint". I'm interested in applying redb to representing the state of large video game worlds, where it's often desirable to capture "saves" at arbitrary times and restore them freely, without invalidating anything. This could be achieved by copying the entire database at the filesystem level, but only at the cost of duplicating potentially large amounts of data. Could the redb savepoint mechanism be extended to only invalidate savepoints on explicit request?

Other useful extensions along the same lines:
- Opening read transactions that start at a savepoint rather than the current state, to allow easy inspection of old data without throwing current data away. This would help e.g. enumerate a user-friendly list of saves.
- Opening *write* transactions that start at a savepoint, and modify the savepoint's state rather than the current state

No idea if these concepts make sense in redb's data model, but they'd be handy!

**Comment by cberner** [comment]
Opening read transactions at a savepoint should be possible. Unfortunately I don't think either of those changes to the way writes work would be easy though. redb's transaction system is designed assuming a linear timeline. Allowing savepoints "from the future" to still exist and be restored would be much more complicated and probably slower.

I'd be careful of relying on savepoints to implement game saves. savepoints prevent redb's garbage collection from running as long as the savepoint exists, so the file will just keep growing

**Comment by Ralith** [comment]
Ah, I didn't fully appreciate that *all* gc would be suspended, rather than just gc of stuff referenced by a live savepoint. Sounds like these requirements are too far removed from the design as it stands to make sense; copying the whole thing is probably the way to go. Thanks for the insight!

**Comment by Ralith** [comment]
Leaving a breadcrumb here: [prolly trees](https://docs.dolthub.com/architecture/storage-engine/prolly-tree) might be a good foundation on which this feature request is feasible. I don't imagine this would be easy for redb to adopt, but perhaps they'll be of interest all the same.
