### ISSUE TITLE
Table level compaction

### ISSUE THREAD

**Issue by eserilev** [cberner/redb#756]
It would be nice to have the option to trigger compaction on the table level. In production systems, performing a full database compaction all at once might not always be feasible due to time constraints and potential performance degradation. Table level compaction would provide more flexibility and opportunities for optimization while minimizing the impact on overall system performance.

**Comment by cberner** [comment]
Unfortunately this isn't possible in redb's design. All the tables are in the same file, so compacting one would have no effect on the file size
