### ISSUE TITLE
Database.check_integrity() is always detecting and repairing corruption

### ISSUE THREAD

**Issue by cikkle** [cberner/redb#761]
Simple test case:

```
fn table_len_test() {
    const DB_TABLE_LEN_TEST: TableDefinition<u32, u32> = TableDefinition::new("len_test");
    let mut db = Database::create("test_len.db").unwrap();

    let integrity = db.check_integrity();
    dbg!(integrity).unwrap();

    for i in 1..5 { 
        let write_txn = db.begin_write().unwrap();
        {
            let mut table = write_txn.open_table(DB_TABLE_LEN_TEST).unwrap();
            table.insert(i, i).unwrap();
        }
        write_txn.commit().unwrap();
    }

    let read_txn = db.begin_read().unwrap();
    let table = read_txn.open_table(DB_TABLE_LEN_TEST).unwrap();
    let length = table.len();

    dbg!(length).unwrap();
}

fn main()  {
    table_len_test();
}
```

This always results in output like:
```
[src/main.rs:423] integrity = Ok(
    false,
)
[src/main.rs:438] length = Ok(
    4,
)
```

Per the documentation, `Ok(false)` indicates repairs were needed and done successfully, but it does this on every run for me. I've never yet seen it pass the integrity check. Changing the call to `create` to `open` to reuse an existing DB when testing gives the same result.

local ext4 filesystem on kubuntu 23.10, if that matters.

**Comment by cberner** [comment]
Oh ya, oops. There's definitely a bug here

**Comment by ppodolsky** [comment]
I have also faced the issue. Integrity check is happening every time on the app restart and it quite fast becomes unmanageble because on large tables it may take minutes or even hours.
