### ISSUE TITLE
Please clarify if `Table.insert()` does replace the attribute if it exists

### ISSUE THREAD

**Issue by abique** [cberner/redb#787]
Hi,

From reading the doc, it is unclear if [`Table.instert()`](https://docs.rs/redb/latest/redb/struct.Table.html#method.insert) does replace or not existing entries.

Thanks,
Alex

**Comment by cberner** [comment]
It does. All the APIs are designed to be similar in function to
`std::collections::BtreeMap`

**Comment by abique** [comment]
OK, thanks for the clarification :+1: .
https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.insert seems to explicitly describe the update scenario.
