### ISSUE TITLE
Impl key and value for String

### ISSUE THREAD

**Issue by casey** [cberner/redb#788]
I noticed that `&str` implements key and value, but `String` doesn't.

**Comment by cberner** [comment]
Ya, I didn't implement that because you would have to insert a &String. And
with &str you can call to_string() when retrieving values, if needed. Do
you have a use case that needs String?

**Comment by casey** [comment]
We have an `Entry` trait which abstracts over complex types that can be loaded and stored from the database:

```
pub(crate) trait Entry: Sized {
  type Value;

  fn load(value: Self::Value) -> Self;

  fn store(self) -> Self::Value;
}
```

`Entry::store` can't borrow self, because it doesn't have any lifetimes, so we couldn't implement `Entry` for something with a `&str` field.
