### ISSUE TITLE
Could `Database` be `Clone`?

### ISSUE THREAD

**Issue by casey** [cberner/redb#789]
I noticed that both fields of `Database` are `Arc`s, and was wondering if the `Database` could implement `Clone`, since it should be cheap, and since creating read and write transactions don't rely on borrowing the `Database`, it should be safe.

**Comment by cberner** [comment]
No. compact() takes a &mut self

**Comment by casey** [comment]
Ahh, darn.

**Comment by tqwewe** [comment]
So can the database be shared throughout an app? If yes, then is it assumed we should wrap it in our own Arc?

**Comment by adamreichold** [comment]
Yes, ideally you can just pass `&Database` around in your components as the methods to start transactions take `&self` and `Database` is `Send + Sync`.

This could mean that you have to wrap it inside an `Arc`, for example if the value is not part of a larger `struct` and has its lifecycle determined by that.
