### ISSUE TITLE
Support Vec<u8> key values, compatibility with other kv db

### ISSUE THREAD

**Issue by GopherJ** [cberner/redb#797]
redb has its own Key, Value traits but some applications may already do this in their own way and all they need is to be able to store:

Key: Vec\<u8\>
Value: Vec\<u8\>

like other embedded databases, to do this in redb we will need to implement Key for Vec<u8> but Vec<u8>  is an orphan type

Key is implemented for &[u8] but since TableDefinition requires 'static lifetime so we can only use &'static [u8] which is not pratical

**Comment by lhallam** [comment]
`&[u8]` works for this, the lifetimes in the `TableDefinition` are overwritten by the correct lifetime for the context using the associated `SelfType` defined in `Key` & `Value`. e.g. `Table::insert` is generic over the lifetimes of the key & value, `ReadableTable::get` is generic over the lifetime of the key and the value has the lifetime of the guard.
