### ISSUE TITLE
Example for multithreaded usage

### ISSUE THREAD

**Issue by lquenti** [cberner/redb#804]
Hi,

could you add an example for multithreaded use? Especially because of this in the README:

> MVCC support for concurrent readers & writer, without blocking

This confuses me with the definition of the struct:

```rust
pub struct Database {
    mem: Arc<TransactionalMemory>,
    transaction_tracker: Arc<TransactionTracker>,
}
```

Having an `Arc` and "concurrent readers" reads to me like I can just clone it to other threads/routes, but it does not implement clone!

- Is it thread safe? 
- Do I have to use an `Arc<Mutex<Database>>` or is `Arc<Database>` enough?
- Is it okay when I just do `Database::open` on the same file twice?

**Comment by geniot** [comment]
Hi, I just looked at the benchmark test, perhaps it can help you further: https://github.com/cberner/redb/blob/master/benches/lmdb_benchmark.rs#L224

**Comment by cberner** [comment]
This file is a good example of concurrent writing: https://github.com/cberner/redb/blob/master/benches%2Fmultithreaded_insert_benchmark.rs

You can't open a database file twice, but concurrent access to the Database and Transaction objects should be safe. As long as it compiles it should be correct 😊
