### ISSUE TITLE
Does redb support spill?

### ISSUE THREAD

**Issue by tisonkun** [cberner/redb#806]
redb states itself an embedded kv stoe, but it still defines a file format and create a data file. I wonder if redb supports spilling data on disk if memory is exhausted.

**Comment by adamreichold** [comment]
redb is not an in-memory key-value store but a persistent database first. It only uses a built-in in-memory cache, c.f. [`set_cache_size`](https://docs.rs/redb/latest/redb/struct.Builder.html#method.set_cache_size), to avoid costly I/O to improve performance.
