### ISSUE TITLE
begin_write() after commit() is very slow, even with Durability::Eventual

### ISSUE THREAD

**Issue by W4G1** [cberner/redb#820]
Starting a new write transaction with `Database.begin_write()` directly after a previous one finished with `WriteTransaction.commit()` takes about 1-2 seconds. I initially thought this had something to do with the default durability, but even when using Durability `Eventual` or `None`, it's still very slow.

- Tested this with a small database and table (100 records) containing small size keys and values
- Calling `Database.begin_write()` without a prior `WriteTransaction.commit()` is very fast and only takes about 3.4µs on my machine.

**Comment by cberner** [comment]
Can you send an example that reproduces the issue? I've never seen that before

**Comment by W4G1** [comment]
I found the problem. I had the previous write tx open for too long because there was also some other intensive process in between, which is why the next write tx had to wait 1-2s. When I removed this in-between process then consecutive write transactions were fast again.

Sorry for the false positive :)
