### ISSUE TITLE
Make UntypedTableHandle constructor public

### ISSUE THREAD

**Issue by tiptenbrink** [cberner/redb#821]
Hi! Thanks a lot for this library.

I was wondering if you could potentially make the `UntypedTableHandle` constructor public? This would allow me to store the handles of a related group of tables so I can easily delete them later without worrying about the types.

**Comment by cberner** [comment]
Oh hmm, lemme think about that. It's probably fine, but I need to look back through the code to see what implications there might be.

In the mean time, have you tried keeping the names of the tables, and then calling `list_tables()` to retrieve the handles and filtering it to the ones with the desired names? It adds an extra step, but I think will do what you want
