### ISSUE TITLE
Unexpected slow batch writes

### ISSUE THREAD

**Issue by sebadob** [cberner/redb#823]
A discussion thread would make more sense for this (I guess), but I can't open one, so I created an issue for this.

I was experimenting with [openraft](https://github.com/datafuselabs/openraft) during the last days and I choosed `redb` as the storage engine for Raft logs. I had huge problems with throughput and in the end I found out, that my `redb` implementation was actually the issue, because it was very slow in comparison to rocksdb for instance. 

In most cases, my `redb` was ~12 times slower, but I am pretty sure that I probably messed up something, I just can't figure out what it could be. Basically, I saw really big latencies when inserting values with redb. I took a look at the benchmarks how you did batch insertions and basically did the same thing:

- begin a write transaction
- open a table
- insert all my values in a `for` loop
- only `commit` at the end of the batch

I started a redb writer on a separate thread that does as less work as possible, so all serialization and such things are on other threads. The writer thread then listens to a channel where it received pre-serialized data that it only needed to `.insert`. The batches come in sequentially because logs order is crucial. The hardware was nowhere near its limitations.

I did some very basic benchmarks and rocksdb was almost as fast as an in-memory implementation (on a very fast SSD raid though), while my redb one was more than an order of magintude slower. When I inserted many values in a row, the latency even increased with my redb approach.

Are there any obvious things I could have missed or where I screwed up somehow? I like redb a lot, especially that it's pure Rust and does not give me the same headaches as rocksdb with compilation and so on.

**Comment by marvin-j97** [comment]
@sebadob Have you set the set_sync option to `true` in RocksDB's WriteOptions? If not, RocksDB only flushes to OS buffers, not to disk, while ReDB always flushes to disk when committing a write transaction.

**Comment by sebadob** [comment]
@marvin-j97 I was just using the defaults and by default sync if off. However, After I write the whole batch, I do a manual flush to disk which sync's everything at once. 

With redb, I though that opening a transaction, inserting many values and only commit at the end would be exactly the same behavior, or am I wrong here and do I need to do something else to achieve the same behavior and speed? Because I don't care if the first logs from the batch get lost during a crash when not the whole batch has been written successfully. The retry after the next startup will write the whole batch anyway.

**Comment by cberner** [comment]
Have you tried increasing redb's cache size, via `set_cache_size()`? redb does not use mmap, so you have to manually configure the maximum cache size

**Comment by sebadob** [comment]
I tested with the cache size as well without a noticeble difference.

I read a lof of docs and source code in the last hours and the big difference is that `rust-rocksdb` is not crash safe by default while `redb` is. I think it's really bad that the rocksdb crate does not mention this explicitly.

When you take a look at facebooks documentation for rocksdb, they mention that rocksdb is crash safe with default settings. However, the rust wrapper's default for the wal sync as mentioned above by @marvin-j97 is set to `false`, which makes rocksdb non-crash safe regarding to the official documentation for it.

When I wait for sync with rocksdb, it is actually ~40% slower during batch insertions in my tests compared to redb. I mean, both of them give me a very low throughput for the Raft when I wait for sync to disk each time, but this at least explains the huge difference I got in the beginning.

Just as a reference, the throughput I am getting with the different implementations with 16 concurrent writers and a data set of 10_240 with localhost network and replication to 3 nodes on a random machine:

- `redb`: 9227ms -> 1_109 write / s
- `rocksdb` sync: 13203ms -> 776 write / s
- `rocksdb` **no** sync: 676ms -> 15_284 write / s

Of course with the Raft group and (localhost) network, there are lots of moving parts with my current setup and its not even closely showing the throughput capabilities of the KV stores, but the logs storage has the biggest impact on the performance. On another bit more powerful 3 year old desktop machine the rocksdb **no sync** reaches over 24k/s.

Nevertheless, the root cause was found, which was non-safe defaults for rust-rocksdb. I will close this issue.

Thanks for your help!

**Comment by marvin-j97** [comment]
> Does this mean `rocksdb` is not crash safe by default and can loose data easily

By default, RocksDB flushes data to the operating system. If the application crashes, the OS can still flush those page to disk. So RocksDB is (application) crash safe (if you trust the OS). However, it is not power loss/system crash safe, because the OS will not get the chance to sync to disk in that situation. So for that you need to enable sync writes, or flush_wal manually with sync=true.

> Flushing the WAL just means flushing it into rocksdbs SST files and it has nothing to do with sync to disk

That would be DB::flush, not DB::flush_wal.

> but the logs storage has the biggest impact on the performance

You are effectively IO-bound in your workload. An SSD needs ~1-2ms for fsyncdata, so you can only get around 500-1'000 persisted, independent writes even on an SSD.

I'm not sure why RocksDB is much slower for sync writes, I'm getting the same result though. I'm sure they fallocate their WAL and only do fdatasync, so it *should* be similar to ReDB. But I haven't really looked deeper than that.
The obvious downside to ReDB's approach is that it generally cannot easily decrease its DB file in size in case you need that, and if you choose to not use fsync, you can't, because it doesn't use a WAL.

**Comment by sebadob** [comment]
> By default, RocksDB flushes data to the operating system. If the application crashes, the OS can still flush those page to disk. So RocksDB is (application) crash safe (if you trust the OS). However, it is not power loss/system crash safe, because the OS will not get the chance to sync to disk in that situation. So for that you need to enable sync writes, or flush_wal manually with sync=true.

Thank's a lot for this clarification. So the risk would be higher if I would use network storage instead of local, but then I have way bigger latency issues anyway.

> You are effectively IO-bound in your workload. An SSD needs ~1-2ms for fsyncdata, so you can only get around 500-1'000 persisted, independent writes even on an SSD.

That makes total sense.

> I'm sure they fallocate their WAL and only do fdatasync, so it should be similar to ReDB.

Their docs say they do. `fsync` is opt-in and only exists for compatibility while `fdatasync` is the default. I tested both of them but did not see any real difference tbh.

Thank you a lot!
