### ISSUE TITLE
Is making queries efficient that is not a key but a value?

### ISSUE THREAD

**Issue by Raj2032** [cberner/redb#827]
Lets say I have this code:

```rust
struct Customer
{
    id: u16,
    name: Name,
    age: u8,
    is_active: bool,
}

struct Name
{
    first: String,
    last: String,
}

fn main()
{
    let customer = Customer{name: Name{first: "John".to_string(), last: "Doe".to_string()},
    age: 32, is_active: false};
}
```

If I wanted to query all the rows that contains the first name as "John", I would have to loop through the entire rows, deserialize each row and then compare, I am not too sure if this is slow and inefficient and I should look for some other databases such as document based or sql?

**Comment by cberner** [comment]
You should think of redb's performance like a `BtreeMap`. Only queries on keys are going to be efficient

**Comment by Raj2032** [comment]
@cberner Fair enough, do you know anything that I can use that will also support nested structures and have a sea-orm like syntax?

**Comment by cberner** [comment]
Maybe something built on sqlite? I don't know anything specific though

**Comment by Raj2032** [comment]
@cberner Fair enough thanks.
