### ISSUE TITLE
Is Database safe for use in Async code?

### ISSUE THREAD

**Issue by kulak** [cberner/redb#837]
Can Database be used from async GRPC service like tonic directly without additional synchronization code?

It seems that it is safe from RUST syntax point of view, because all the mutability occurs in write transaction. Write transaction is usually  scoped to the function body, so there should be no problem.  

The code itself is 100% sync and that makes me wounder if it is async safe.

---

Is Database safe from multiple processes accessing it?  Example would be Common Gateway Interface processing model.

**Comment by cberner** [comment]
It supports multiple threads, but not multiple processes. You will get an error if you try to open it, concurrently, from multiple processes

**Comment by adamreichold** [comment]
> The code itself is 100% sync and that makes me wounder if it is async safe.

Note that since all I/O uses blocking system calls, you would generally wrap all interactions with redb using your runtime's method to make such calls, e.g. [`spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html) when using Tokio.
