### ISSUE TITLE
Busy loop during compaction

### ISSUE THREAD

**Issue by adamreichold** [cberner/redb#852]
After upgrading our service from redb version 2.1.1 to 2.1.2, we are seeing busy loops during compaction, i.e. compacting starts and continuously rewrites pages as fast as the disk allows, but never finishes whereas the same code base finishes compaction in a minute or so using version 2.1.1.

I did modify our code to run `check_integrity` immediately after opening the database as suggested in the release notes which yields `Ok(true)`.

The effect does seem to be reproducible insofar it is triggered whenever we delete a significant amount of entries before starting compaction.

Please let me know what additional information I should provide to help you understand the issue. (The source code is available via [OpenCoDE](https://gitlab.opencode.de/umwelt-info/metadaten/-/blob/main/src/umthes/cache.rs) and I can share the database file which currently clocks in at 600 MB.)

**Comment by cberner** [comment]
Uh oh, ya I changed the compaction code quite a bit to fix some issues. In previous versions, `compact()` didn't actually compact the whole database, and likely only compacted a small amount of it. So my guess is that it's now slow and will finish eventually.

However, looking at the code again I realize that the implementation in 2.1.2 could be extremely slow (quadratic in the size of the database), so I'm going to implement a different approach. Might take a bit, but I'll let you know as soon as that's ready to try out

 Have you observed this on a small database? Say one with only hundreds or thousands of key-value pairs?

**Comment by adamreichold** [comment]
> Have you observed this on a small database? Say one with only hundreds or thousands of key-value pairs?

No, but I have not tried. Will do and report back here.

**Comment by adamreichold** [comment]
> So my guess is that it's now slow and will finish eventually.

This is possible, but I did let it run for three hours without it finishing. Of course, quadratic behaviour can be like that.

**Comment by cberner** [comment]
I just added compaction to the benchmark suite, and ya it's **crazy** slow. Even slower than I expected. 43secs for a database that only had ~1000 pairs in it. https://github.com/cberner/redb/pull/853

**Comment by adamreichold** [comment]
I tried using a database containing a few hundred keys and that indeed works and is reasonably quick. So this would support a problematic performance profile, but not an actual live lock.

**Comment by cberner** [comment]
I think this should be fixed now. Can you give `master` a try and see if it works for you?

**Comment by adamreichold** [comment]
I can confirm that the current `master` branch does resolve the issue, running only slightly longer than version 2.1.1 on a 530 MB database.

As an aside, I found this while testing a size optimization which reduces the size of my values from 20-25 bytes to 15-20 bytes after some of my tables. However, I am not seeing a size reduction even after compaction finishes.

Is it possible that allocator size classes or something like that mean that the change is too small too meaningfully reduce the space used to store values?

**Comment by cberner** [comment]
Can you try printing out the results of `WriteTransaction::stats()` before and after your change? That'll tell you how many pages are being used for storage: if that number doesn't go down, then ya there would be no change even after compacting

**Comment by adamreichold** [comment]
So these are the stats before migration

```rust
DatabaseStats {
    tree_height: 5,
    allocated_pages: 85371,
    leaf_pages: 83652,
    branch_pages: 1711,
    stored_leaf_bytes: 210034271,
    metadata_bytes: 10457858,
    fragmented_bytes: 129162911,
    page_size: 4096,
}
```

and these are after the migration and compaction

```rust
DatabaseStats {
    tree_height: 5,
    allocated_pages: 88327,
    leaf_pages: 85850,
    branch_pages: 2475,
    stored_leaf_bytes: 191256099,
    metadata_bytes: 10498067,
    fragmented_bytes: 160029130,
    page_size: 4096,
}
```

So if I am reading this correctly, I have fewer `stored_leaf_bytes`, i.e. my values did indeed get smaller, but I have more `fragmented_bytes` and `branch_pages` which even yields more instead of fewer `allocated_pages`.

Is there anything I can do better about the migration? I am currently rewriting the tables in a single pass, c.f. https://gitlab.opencode.de/umwelt-info/metadaten/-/blob/52d3245ec6c2dd224d7486b8872f217c7f7cfb1b/src/umthes/cache.rs#L102

**Comment by cberner** [comment]
Huh, that's a bit surprising, but certainly not impossible. The btree data structure splits as pages become full, so small changes in the total amount of data or distribution of value sizes can have small and difficult to predict changes in the total tree size.

Ya, the way you're doing it seems fine to me. Nothing obvious that you can improve

**Comment by adamreichold** [comment]
I am sorry for nagging you about this but I am planning a dependency bump and would be glad if this fix could be released to crates.io? Thanks!

**Comment by cberner** [comment]
Ya, for sure. Just released it!
