### ISSUE TITLE
Reading values from untyped tables.

### ISSUE THREAD

**Issue by oiwn** [cberner/redb#867]
Hello! Thank you for your amazing database. I'm using redb on couple of internal cli tools and decided to write some kind of TUI to look tables and key-value pairs ( https://github.com/oiwn/redb-tui ) , but unfortunately stuck into https://github.com/cberner/redb/issues/741

The problem is similar, there is no way to read k-v pairs from untyped tables or at least have them as [u8] slices. Could you suggest possible solutions? 

Also I can see errors like

```
Err(TableTypeMismatch { table: "users", key: TypeName { classification: Internal, name: "&str" }, value: TypeName { classification: Internal, name: "u32" } })
```

Does it mean database aware about table types?

**Comment by adamreichold** [comment]
The type names and fixed sizes of keys and values are checked, c.f.

https://github.com/cberner/redb/blob/738b7ab361dfef6b1b6f12a484b41a8a7dff4da1/src/tree_store/table_tree_base.rs#L161

I don't think this can be relied on for memory safety, can it? I mean, accidental collisions between different programs using the same type names and no fixed size are still possible. So it might make sense to provide a code path side-stepping it?

A more limited and harder to misuse solution might be if `ReadOnlyUntypedTable` would gain `get` and `range` methods that essentially mirror the ones from `ReadOnlyTable` with fixed types `K = [u8]` and `V = [u8]`.

**Comment by oiwn** [comment]
@adamreichold I'm not sure I understand, it looks like types are known on internal level?

Btw possible solution (suggested by collegue) would be to use this tiny wrapper around redb to get binary representation of key-value pairs: 

https://github.com/rustshop/redb-bincode

**Comment by adamreichold** [comment]
> @adamreichold I'm not sure I understand, it looks like types are known on internal level?

The database stores the type names and checks those against what your `Key/Value` trait impls provide to avoid accidentally loading a table using mismatching types. You can check this by manually implementing `Key/Value` and changing nothing but the name which will mean you cannot open existing tables even though the data itself has not changed at all.

**Comment by cberner** [comment]
redb is strongly typed, so reading from an untyped table is not allowed. 

If you want to implement a TUI, I'd recommend making your own fork and adding the features you need. Otherwise, you could try to implement a very large `match` on both the key and value TypeName that you get in the error message
