### ISSUE TITLE
Purpose of lifetime of SelfType?

### ISSUE THREAD

**Issue by cwahn** [cberner/redb#908]
I have look around the documentation and a bit of code and get wondered about the purpose of lifetime of `SelfType` of `Value` trait. 

At the beginning I figured that it is for providing reference of value with life time of `AccessGuard` rather than copying it. 

However, soon I found [this issue](https://github.com/cberner/redb/issues/869), using `'static` lifetime for `SelfType`.
Also, if you search for `SelfType` in repository, the they are all form of below;
```rust
impl Value for SomeType {
    type SelfType<'a> = SomeType // What about 'a?
    ...
}
``` 
And I have check that indeed there is no problem to return the result of `AccessGuard::value()` out of the scope of the `AccessGuard` and even the table it is from. 

So at this point, I wonder what is the purpose of lifetime of `SelfType` of `Value` trait is for, and if `AccessGuard::value()` occurs copy of data?

**Comment by cberner** [comment]
It's used for types that borrow the input buffer. For example, `&str` https://github.com/cberner/redb/blob/6e9a8118cc856fbecc670a053bc60365b0618da2/src/types.rs#L447-L449

**Comment by cwahn** [comment]
Thank you for the quick reply. 

I know this is not a discussion but an issue, but there is no discussion, keep asking here. 

In that case, it is nothing to do with read without copy and value being copied on call of `AccessGuard::value()` is intended action right?

**Comment by cberner** [comment]
Well, it depends on the type. For a u64, yes it is copied. For a `&str` is it not copied and it borrows from the buffer inside `AccessGuard`

**Comment by cwahn** [comment]
Okay, what about the `String` and `Vec`? These are my actual question. 
Copy of the underlying data on read is intended design?

**Comment by cberner** [comment]
You can find the code for Vec here: https://github.com/cberner/redb/blob/6e9a8118cc856fbecc670a053bc60365b0618da2/src/complex_types.rs#L46
