### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by raphjaph** [cberner/redb#909]
Just wanted to ask if there are any plans to make a new release soon. I would love for our users of [`ord`](https://github.com/ordinals/ord) to enjoy work done in the last couple commits, especially #893.

Thanks!

**Comment by cberner** [comment]
Ya, sure thing. I'll get one out this week

**Comment by cberner** [comment]
2.3.0 is out now!

**Comment by raphjaph** [comment]
Awesome, thanks!
