### ISSUE TITLE
Should `cache_metrics` be exposed?

### ISSUE THREAD

**Issue by JamesHinshelwood** [cberner/redb#910]
I see in `cached_file.rs` that `redb` keeps track of cached read misses and hits if the `cache_metrics` feature is enabled. However, I don't see any way of exposing that data to the application?

It would be quite useful to us to see the hit-rate, so we know if our cache size is large enough. Did you plan to expose these metrics in the future?

**Comment by cberner** [comment]
Just put up a PR for this. Lemme know if that covers your use case? I'm trying to expose the minimum amount of information at the moment, because I'll probably redo some of the cache implementation in the future

**Comment by JamesHinshelwood** [comment]
Thanks, that's exactly what I was looking for.
