### ISSUE TITLE
Read + Write in single Transaction

### ISSUE THREAD

**Issue by d47081** [cberner/redb#921]
I want an example for situation, where both read/write operation should be covered in single transaction.

For example, I can't call `get` method in the `begin_write` transaction context.
Thanks

**Comment by jack-samo10000** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the example to demonstrate both read and write operations within a single write transaction. This includes reading a value, incrementing it, and writing it back to the database.

You can review changes in this commit: https://github.com/jack-samo10000/cberner-redb-921/commit/84da32153699b7b259c66d7018986d1a10562ca0.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
