### ISSUE TITLE
Add a non-blocking way to begin a `WriteTransaction`

### ISSUE THREAD

**Issue by matt-cornell** [cberner/redb#924]
I'm working on an app that could have multiple concurrent writers to a single database, and they need to hold onto the transaction for a long time. To make things more asynchronous, I'd like to have methods like `Database::try_begin_write` and/or `Database::try_begin_write_timeout` that return `Option<Result<WriteTransaction, TransactionError>>` (or maybe another variant could be added to `TransactionError`) and are guaranteed to not block. Having methods like these available would also be a step toward the async API.

**Comment by cberner** [comment]
Have you tried using a separate `Mutex` or `Condvar`? I generally don't add APIs for functionality that the user can build  themselves

**Comment by matt-cornell** [comment]
Now that I look at it again, I think the issue was really me having transactions open for that long rather than any of your API; I'm going to try to rework some of my stuff so it's not a problem anymore.
